### ISSUE TITLE
Sample data from the People Data Feed and Open Access Monitor

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#10]
Sample PUBS-ATOM files that I have seen so far do not include data from the people data feed or the open access monitor. 

As a result, I can't assess whether or not these sources contain metadata that will be hard to map.

Would it be possible to provide this in the sample API XML files (or however that data will be fed to the crosswalks?

**Comment by AndrewBennet** [comment]
I'm not quite sure what you mean by data from the open access monitor - could you clarify?

And by people data feed, do you mean the metadata of the users linked to the publication? If so, that is present in the current single sample file: https://github.com/tomwrobel/ora_data_model/blob/master/elements_xwalks/xwalk-out/input-publication-9598.xml#L213

I will generate some more examples later today and upload them 👍

**Comment by jjpartridge** [comment]
Hi Andrew, 

People Data Feed is our reference for the HR User Feed - e.g. user information, this is a BizTalk connection with Research Services and IT Services, which populates the user table. 

As for the Open Access Monitor (OAM), the question is whether there is any data from the OAM module that is likely to be fed back to the repository (e.g. compliance or REF exception information), or whether the OAM is reading information only from the data in Elements and will not pass anything onto the repository.

Hope that makes sense - Tom correct me if i'm wrong!

**Comment by AndrewBennet** [comment]
Thanks - that's good to know.

The HR User information for linked users is available - see https://github.com/tomwrobel/ora_data_model/blob/master/elements_xwalks/xwalk-out/input-publication-9598.xml#L235

There is _some_ OA info (policy exceptions, library statuses) included in the XML that the xwalks work with. Compliance info, however, _isn't_ exposed in this. Trying to crosswalk the compliance status wouldn't be recommended anyway: it depends on the current date, as well as the presence of records in external systems, so the value is likely to be incorrect very quickly.

Below is a sample of the OA data available in the input XML:

    <api:oa>
      <api:oa-policy-exception-type>Tech3</api:oa-policy-exception-type>
      <api:oa-policy-exception-comment>Hyrax deposit has not yet been developed!</api:oa-policy-exception-comment>
      <api:oa-policy-exceptions>
        <api:oa-policy-exception>
          <api:type>Tech3</api:type>
          <api:comment>Hyrax deposit has not yet been developed!</api:comment>
        </api:oa-policy-exception>
      </api:oa-policy-exceptions>
      <api:library-status status="full-text-received" status-display-name="Full text received">
        <api:last-updated-when>2019-02-06T17:01:58.59+00:00</api:last-updated-when>
        <api:note>Library status changed to 'Full text received' on 06/02/2019 by Daniel Hook.</api:note>
      </api:library-status>
    </api:oa>

**Comment by tomwrobel** [comment]
I've added crosswalk documentation for People from 83749. I'll look at open access mapping when I get to 9598.

The new crosswalk documentation represents a substantial update, so is worth looking at!

**Comment by tomwrobel** [comment]
@jjpartridge Could you look through the sample OA monitor output above and in https://github.com/tomwrobel/ora_data_model/blob/master/elements_xwalks/xwalk-out/input-publication-9598.xml#L235 and let me know if there's anything here we want to crosswalk into the data model. I'm not entirely sure what all of these fields do, and I don't have an existing crosswalk to fall back on for information!

**Comment by jjpartridge** [comment]
@tomwrobel 

<api:oa>
      <api:oa-policy-exception-type>Tech3</api:oa-policy-exception-type>
	  	  
	        <api:oa-policy-exception-comment>Hyrax deposit has not yet been developed!</api:oa-policy-exception-comment>
		  
      <api:oa-policy-exceptions>
        <api:oa-policy-exception>
          <api:type>Tech3</api:type>
          <api:comment>Hyrax deposit has not yet been developed!</api:comment>
		  
        </api:oa-policy-exception>
      </api:oa-policy-exceptions>
      <api:library-status status="full-text-received" status-display-name="Full text received">
        <api:last-updated-when>2019-02-06T17:01:58.59+00:00</api:last-updated-when>
        <api:note>Library status changed to 'Full text received' on 06/02/2019 by Daniel Hook.
</api:note>
      </api:library-status>
	    
    </api:oa>
	
	<api:neighbourhood>
      <api:relationships>
        <api:relationship id="9667" type-id="8" type="publication-user-authorship"

**Comment by tomwrobel** [comment]
@jjpartridge shall we discuss what fields these would map to tomorrow?

**Comment by jjpartridge** [comment]
Thanks for fixing the edit above. Yes we can add to discussion tomorrow. Not sure it is coming through very well, but there are two questions in the above, one for @AndrewBennet  and one for @eugeniobarrio

**Comment by jjpartridge** [comment]
@AndrewBennet actually I see example of grant info in : https://github.com/tomwrobel/ora_data_model/blob/master/elements_xwalks/xwalk-out/input-publication-83749.xml so that answers part of the question, do you have an example of publication to publication relationships?

**Comment by AndrewBennet** [comment]
@jjpartridge - yes, there are some publication-publication link types available. The names of these link types are as follows:

| Name                                 | LinkType      | InverseLinkType    |
|--------------------------------------|---------------|--------------------|
| publication-publication-derivative   | Derivative of | Derives            |
| publication-publication-supersedence | Supersedes    | Is superseded by   |
| publication-publication-supplement   | Supplements   | Is supplemented by |
| publication-publication-correction   | Corrects      | Is corrected by    |

However, the availability of these link types can be controlled. I believe that by default only the `Derivative of / Derives` link type is available to users.

The representation of this in in the API serialisation would be very similar to how the linked grant object is serialiased (just with publication object instead)

**Comment by tomwrobel** [comment]
@AndrewBennet do you have examples of the publication-publication relationship in a record? I can write mappings (to related_items)

**Comment by AndrewBennet** [comment]
I will prepare some an upload them shortly

**Comment by AndrewBennet** [comment]
I've pushed an example of a publication with several publication-publication relationships (https://github.com/tomwrobel/ora_data_model/blob/master/elements_xwalks/xwalk-out/input-publication-86457.xml)

**Comment by tomwrobel** [comment]
@AndrewBennet I've created a new METS file with that record, and I've updated the mappings xml file to include new mappings.

We're a bit concerned by what happens when a related publication has no DOI.

In ORA, and in the data model, we deal with this by generating a human-readable citation for the related work. This is placed in related_items\__related_item_citation.

Looking at Symplectic Elements, there are a number of places where a citation string is generated for a PUBS item. Would it be possible to include a citation string here for mapping?

**Comment by jjpartridge** [comment]
@AndrewBennet @tomwrobel Apologies for adding to a closed ticket, but thinking about testing and pushing values back to SE. With regards to exceptions in this instance, would the value that SE is expecting to see be: "Access1"; "Deposit1", "Other"; "Tech1" etc.?

Where as in ORA these are currently recorded as the text values of the exceptions, e.g. "Publisher embargo too long" or "Publisher does not allow OA".

Do these values need to be mapped so that they can be understood by the crosswalk? I assume for testing we should look to send the SE values in order to see a change within OA Monitor for example?

Thanks, 
Jason
