### ISSUE TITLE
Complete sample METS file

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#11]
@AndrewBennet @anusharanganathan 

I'm going to convert the MODS sample file into METS as, hopefully, a candidate final version. I hope to do this today.

I've pushed an update today against the upcoming MODS 3.8 schema, as I've managed to persuade them to allow for extension-like elements inside mods:affiliation. This removes one of the customisations to the MODS schema and leaves us with only one customisation which, I hope, we'll also find a way to resolve.

From now on, I'll be putting a changelog into the document so that you know what's changed. I'll also create an issue for every new or changed field so that we can keep abreast of any changes (and to discourage me from tinkering)

For ORA purposes only, the relevant Trello tracking ticket is https://trello.com/c/w3dt6U6J/

**Comment by tomwrobel** [comment]
We now have the complete sample METS file in place. Could you please take a brief look.

@AndrewBennet I'll be discussing w. Anusha how relevant this is to you, so there's no action needed immediately. It's possible that we can proceed with MODS and binary file metadata as separate entities as far as Symplectic is concerned. If not, we can still use separate binary file metadata files for setting/getting binary file metadata - we'd have to have a brief think about what the METS file you sent would look like (it would probably have none of the binary files or their metadata in it). 

@anusharanganathan we need to discuss whether or not the crosswalk/Sword2 plugin can be made sufficiently modular to output either MODS or METS on request. If so, we can keep the current approach for Symplectic crosswalking.

**Comment by tomwrobel** [comment]
@AndrewBennet 

After discussion with Anusha. We do want to move forward with METS rather than MODS as the object/record level metadata format.

This isn't actually that complicated, but the files are quite large. So, for clarity, below is what we want to do. I'm happy to discuss modifications!

Once we're all happy, I'll be deprecating the MODS sample file.

Sections for clarity
- The Old MODS structure
- The new METS structure
- Record creation METS
- Record read METS
- Binary file metadata creation and reading

## The Old MODS structure

- Record metadata:
  - Default fields
  - Identifiers
  - Event related metadata
  - Origin Info (dates and place of publication of print item)
  - Related Items
  - Rights and licenses
- Contributions and roles:
  - Commissioning bodies
  - Contributors
  - Contributors et al
  - Copyright holders
  - Funders
  - Publishers
- Work-type specific metadata
  - Book, book chapter, edited book, event proceedings
  - Journal article
  - Patent
  - Series
  - Thesis
  - Working paper
- Admin metadata:
  -  General admin
  - Open access admin
  - Thesis specific admin
  - Embargo details
- Binary file metadata
    
## The new METS structure

- dmdSec (descriptive metadata section) for the record
  - Record metadata (and all children)
  - Contributions and roles (and all children)
  - Work-type specific metadata
- dmdSec for each binary file
  - Binary file metadata 
- amdSec (administrative metadata section) for the record
  - Admin metadata (and all children)

## Record creation METS

For record creation, you do not need to specify binary file metadata. The METS file would just contain

- dmdSec (descriptive metadata section) for the record
  - Record metadata (and all children)
  - Contributions and roles (and all children)
  - Work-type specific metadata
- amdSec (administrative metadata section) for the record
  - Admin metadata (and all children)

## Record reading METS

For record reading, you would get a complete METS file (with binary file information if any binary files have been deposited)

## Binary file metadata creation and reading

For binary files, metadata can be set and read by sending/receiving JUST the binary file metadata (i.e. an ora:repository_file), as before. The structure of this XML is documented by the binary file metadata section in the METS file.

**Comment by AndrewBennet** [comment]
I'm pretty sure this will be fine on our end - I'll obviously need to make some adjustments to the reading/writing of metadata, but I don't expect that to be a large change. If this is definitely the plan I will go ahead and start to make those changes 👍

**Comment by tomwrobel** [comment]
Dear Andrew

Yes, this is now the plan, if you're on board with it that's great.

Although it seems a faff, this has *considerable* benefits on our end. and it means that the descriptive metadata section, which is where most of the metadata exchange with Symplectic takes place, is almost all standard MODS (and hopefully will be completely standard MODS within the next six months).
