### ISSUE TITLE
repository-status

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#113]
For SE `repository-status` the harvest crosswalk looks for a `record_publication_date` value (value will be set to `Public`) or a `record_review_status` mapped as follows:

```
<xwalk:value-map name="repository-status">
      <xwalk:value-mapping from="Deposited" to="Private"/>
      <xwalk:value-mapping from="In review" to="Private (in review)"/>
      <xwalk:value-mapping from="Public" to="Public"/>
      <xwalk:otherwise-mapping to="Unknown"/>
    </xwalk:value-map>
```
In testing, the Hyrax value is `Complete (file available)`

Q for ORA team: what are the expected values for `record_review_status`? Do we need to amend the value mapping?

**Comment by jjpartridge** [comment]
Here are the record_review_status' that will be available for a reviewer to apply to a record in Hyrax:

  - id: Complete (file available)
  - id: Complete (file indefinite embargo)
  - id: Complete (no files on record)
  - id: Under embargo (until given date)
  - id: Under embargo (until publication)
  - id: Under embargo (until publication of related item)
  - id: Waiting for response (from author)
  - id: Waiting for response (from publisher)
  - id: Check back (for publication information)
  - id: Check back (for release of VoR)
  - id: Incomplete or in-progress
  - id: Other (please specify)
  - id: Dispensation requested
  - id: LTS not yet granted
  - id: Not eligible (for deposit to ORA)
  - id: Error
  - id: Tombstoned
  - id: Deleted

However they should all roughly equal the states you have indicated (and are also mentioned at:  https://github.com/tomwrobel/ora_data_model/issues/2)

Essentially if there is a record_deposit_date and no record_publication_date, but also no 'claim' status then the object is "Deposited" only
If there is a record_deposit_date, no record_publication_date, but there is a 'claimed' status then the record is "In Review"
If there is a record_deposit_date, and a record_publication_date, with or without a 'claimed' status then the record is "Public"

A 'claimed' status is not just that "Claim" has been applied, but that a reviewer has been recorded against the record in any form or that (in ORA3 terms) an xml_ora datastream is present.

@tomwrobel has likely already caught these rules to create the three states you are mapping.

**Comment by tomwrobel** [comment]
@mrdsaunders there are no mappings for these statuses, and I haven't caught these rules. I suspect that the Hyrax-side discussion moved on and I didn't update. I think I was under the impression that this was a computed field, derived from the record history, rather than an actual field.

@jjpartridge we may need mappings for all of these states to symplectic ones. However, I suspect that Jason's logic-based approach above is a better one. With the following (discussed w. Jason) definitions:

- if there is no record_publication_date OR record_review_status: Private
- if there is NO record_publication_date and ANY record_review_status: Private (In review)
- If there is a record_publication_date: Public

**Comment by jjpartridge** [comment]
@mrdsaunders You then don't need to read directly values from record_review_status into repository_status instead the value is calculated - does that make sense?

**Comment by mrdsaunders** [comment]
Yes, thanks to all. Crosswalk updated:
```
if there IS a record_publication_date
    status 'Public'
else if there IS a record_review_status:
    status 'Private (In review)
else:
    status 'Private'
```
