### ISSUE TITLE
Datamodel changes to 2.0rc5

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#12]
I'm uploading an update to the ORA Data Model. We're *very* close to locking this down to 2.0.

Changelog:

    07/02/2019: Update to MODS 3.8, Update to 2.0rc5
    - Changed to MODS 3.8 schema
    - Changed mods:name/mods:extension/ora:affiliation to mods:name/mods:affiliation/ora:affiliation
    - Added binary_files__file_order
    - Added record_identifiers__record_identifier_scheme and record__identifiers__record_identifier

**Comment by jjpartridge** [comment]
@tomwrobel  is this now covered by #32 ?

**Comment by tomwrobel** [comment]
@jjpartridge we are, and this was an announcement in any case. Closing
