### ISSUE TITLE
File embargo information not being sent/crosswalked

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#120]
When depositing a file in SE, there is an error in Step 2. To review:

## Step 1 of 3

I choose the file and select its Rioxx Version, this is working.

## Step 2 of 3

I add additional information by specifying an embargo, both a period and a comment: this is not being received by Hyrax

## Step 3 of 3

I agree a deposit licence and deposit: this is working

## Debugging

I've deposited a file with an embargo and embargo comment and verified that this information is not being passed to Hyrax. I've also checked the METS xml file that is being received by Sword2, and there is no relevant information in the METS file. I've checked the binary file metadata file that  is being recieved by Sword2, and there is no relevant information in this file either. An example of that file is below:

```
<ora:repository_file xmlns:ora="http://ora/terms/"><dc:title xmlns:dc="http://purl.org/dc/elements/1.1/">Workflow_status (1).xlsx</dc:title><rioxxterms:version xmlns:rioxxterms="http://www.rioxx.net/schema/v2.0/rioxx/">NA</rioxxterms:version></ora:repository_file>
```

Note that filename and RIOXX status is being passed, but there is no file embargo or file embargo comment, and there should be. This may be one for Andrew Bennett

**Comment by mrdsaunders** [comment]
In the deposit crosswalk, rioxx version (`file.BSPWIN685version`, I assume from the deposit dropdown) and file name (`file.name` are passed via  `<xwalk:field-mapping to="ora:repository_file">`. 

I can amend this if I can find in the schema what the fieldnames for embargo and embargo comment are. I'll see what I can do and contact Andrew otherwise. 

Hopefully:
file.requested-embargo-info
file.comment

**Comment by mrdsaunders** [comment]
Are these in the SE -> ORA mappings or ORA fields -> METS?

If you can signpost me or let me have the ORA field names and example mets I can do the crosswalks.

**Comment by tomwrobel** [comment]
The relevant fields are in the binary file metadata section:

```
<ora:repository_file>
    <ora:embargoComment>field:binary_files__file_embargo_comment</ora:embargoComment>
    <ora:embargoPeriod>field:binary_files__file_embargo_period</ora:embargoPeriod>
</ora_repository_file>

**Comment by mrdsaunders** [comment]
Apols, I do in fact see the embargo period field in the mapping as SE field `p-requested-embargo-period` (not the name I assumed from the schema). The comment is not in the mapping, but I could guess the other as p-embargo-comment.

Tom if you can test this again, I'l check with Andrew Bennett for the name if that doesn't work.

**Comment by mrdsaunders** [comment]
From Andrew Bennett:
The fields are `requested-embargo.display-name` and `requested-embargo.comment`

```
The embargo "fields" (in quotes as they are not really fields, but behave like fields) are at the item level rather than the file level, but you can access item level fields within the file-metadata-map
```

**Comment by mrdsaunders** [comment]
Crosswalk updated, tested, passed.
