### ISSUE TITLE
Problem crosswalking to <mods:recordInfo>

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#123]
The Deposit crosswalk should write the value from SE field `confidential` into `mods:recordInfoNote type="confidential_report"` and also write the value `'Symplectic Elements'` to `mods:recordContentSource` (the latter as per [#83](https://github.com/tomwrobel/ora_data_model/issues/83)):
```
<xwalk:field-mapping to="recordInfo">
      	<xwalk:field-source subfield="recordContentSource" value="Symplectic Elements"/>
        <xwalk:field-source subfield="recordInfoNote">
        <xwalk:field-source subfield="@type" value="confidential_report"/>
        <xwalk:field-source from="confidential"/>
      </xwalk:field-source>
      </xwalk:field-mapping>
```

In SE test screen the mets are created:
```
<mods:recordInfo>
                <mods:recordContentSource>Symplectic Elements</mods:recordContentSource>
                <mods:recordInfoNote type="confidential_report">true</mods:recordInfoNote>
              </mods:recordInfo>
```
However in ORA mods:recordInfo shows the following:
```
<mods:recordInfo>
        <mods:recordInfoNote type="record_requires_review">true</mods:recordInfoNote>
</mods:recordInfo>
```
Is there perhaps an issue on the ORA side which is not ingesting the mets from the deposit crosswalk? Is the record_requires_review perhaps overwriting the other data?

**Comment by tomwrobel** [comment]
@mrdsaunders I've just checked the crosswalks, and those values are being ingested and returned.

Can you retest?

**Comment by mrdsaunders** [comment]
So as an example, Pub ID `1012040`  `uuid_7909b91c-e19e-4515-8d94-c8fc9254f2ce`.

@tomwrobel I still have that issue. The SE crosswalk test screen (entering that PubID) gives:
```
<mods:recordInfo>
        <mods:recordContentSource>Symplectic Elements</mods:recordContentSource>
</mods:recordInfo>
```

However, the METS for the resulting uuid show:
```
<mods:recordInfo>
        <mods:recordInfoNote type="record_requires_review">true</mods:recordInfoNote>
</mods:recordInfo>
```

**Comment by tomwrobel** [comment]
The issue for recordContentSource (and I suspect all of the record info fields) is that they are being crosswalked into the wrong section of the METS. They're being put into the dmdSec element, with all of the descriptive metadata, rather than the amdSec element with the administrative metadata.

**Comment by mrdsaunders** [comment]
From [ticket](https://support.symplectic.co.uk/support/tickets/241268) to Andrew Bennett:
```
Administrative metadata comes from a field-map with name "administrative-metadata" (if present). This is currently a hardcoded Hyrax quirk, and is not documented yet. We may in future end up switching it to be a bit more formal - perhaps the field-map-selector could reference it via an attribute, just like it does for the regular metadata. For now though, if you add / update field-mappings inside a field-map called "administrative-metadata" you should achieve this.
```
