### ISSUE TITLE
Map contributor affiliations

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#124]
In ORA terms, a contributor is any person making a contribution to the work, e.g. SE author, editor, translator, contributor or impersonator. 

At present, contributor affiliations are not being presented to ORA in the METS file. Therefore no contributor affiliations (contributor = any person making a contribution to the work, e.g. author, editor, translator, contributor or impersonator)

It may be that the wrong fields are being specified in the mapping. It may be that there is a problem with the crosswalk engine. However, this needs to be fixed.

@jjpartridge can you check that the relevant crosswalk instructions are correct? If so, please pass the ticket to @mrdsaunders and we'll work on the crosswalk itself.

```
 <!-- 
        ===========================================
        CONTRIBUTOR FIELDS FROM API RELATIONSHIPS
        ===========================================
        
        All of these field names are found within an api:relationship[@type='publication-user-authorship']/api:object['@category=user'] 
        with an @id corresponding to the api:links/api:link[@type='elements/user']/@id of a pubs:person or the @id of an api:depositor.
    -->
        <symplectic_field name="email-address"><ora_field>contributors__contributor_email</ora_field></symplectic_field>
        <symplectic_field xpath="api:organisation-defined-data[@field-number]='1']"><ora_field>contributors__division</ora_field></symplectic_field>
        <symplectic_field xpath="api:organisation-defined-data[@field-number]='2']"><ora_field>contributors__group</ora_field></symplectic_field>
        <symplectic_field name="primary-group-descriptor"><ora_field>contributors__department</ora_field><note>If this field is set, then contributors__institution should be set to "University of Oxford"</note></symplectic_field>
        <symplectic_field name="department"><ora_field>contributors__sub_department</ora_field></symplectic_field>
        <symplectic_field xpath="@proprietary-id"><ora_field>contributors__institutional_identifier</ora_field></symplectic_field>
        <symplectic_field xpath="api:user-identifier-associations/api:user-identifier-association">
            <if test="@scheme='orcid'">
                <ora_field>contributors__orcid_identifier</ora_field>
            </if>
            <else>
                <ora_field>contributors__contributor_identifiers__contributor_identifier_scheme="@scheme"</ora_field>
                <ora_field>contributors__contributor_identifiers__contributor_identifier</ora_field>
                <note>The scheme for the user-identifier-association should become the value of the contributor_identifiers_scheme. However email-address should not be mapped</note>
            </else>
        </symplectic_field>
        <symplectic_field xpath="api:neighbourhood/api:related-groups/api:related-group[@id='1'][@membership_type='implicit']"><if test="Another personal affiliation is set, but no value is set for contributors__institution">
            <ora_field>contributors__institution</ora_field>
        </if></symplectic_field>
        <symplectic_field name="figshare-for-institutions-user-account-id"><ora_field>contributors__institutional_identifier</ora_field></symplectic_field>

<!-- Later instructions -->
 <oxford_symplectic_field number="01" name="division-affiliation"><ora_field>contributors__division</ora_field></oxford_symplectic_field>
        
        <oxford_symplectic_field number="02" name="Academic Affiliations"><ora_field>contributors__institution</ora_field></oxford_symplectic_field>
        
        <oxford_symplectic_field number="03" name="College Affiliation"><ora_field>contributors__oxford_college</ora_field></oxford_symplectic_field>
        
        <oxford_symplectic_field number="04" name="Job Description"><ora_field>contributors__roles__role_title</ora_field></oxford_symplectic_field>
        
        <oxford_symplectic_field number="05" name="ORCID"><ora_field>contributors__orcid_identifier</ora_field></oxford_symplectic_field>
        
        <oxford_symplectic_field number="06" name="Department Affiliation"><ora_field>contributors__department</ora_field></oxford_symplectic_field>
        
        <oxford_symplectic_field number="07" name="Sub Unit Affiliation"><ora_field>contributors__sub_unit</ora_field></oxford_symplectic_field>
      

```

**Comment by jjpartridge** [comment]
From a brief look and check in with Dave these may be outdated values with regards to the symplectic_field number and the columns in the people table. 

What we want is a mapping <--> for these fields in ORA:
(ORA = SE)
contributor_type = @type='personal'
family_name = Last name
given_names = First name
initials = Initials
display_name = Abbreviated name
preferred_family_name = User Defined Last name
preferred_given_name = User Defined First name
preferred_contributor_email = Email
contributor_email = Email
contributor_website_url = author-url
orcid_identifier = ORCID (Generic05) (but there maybe something clever already in the crosswalk with the scheme details for this)
contributor_identifier = (Associated identifiers such as Scopus id etc)
contributor_identifier_scheme = linked with above
contributor_record_identifier = Generated with ORA
institutional_identifier = Username (SSO)
role_title = authors, editors, etc
role_order = Generated by ORA
et_al = ORA Generated
institution = If author match and 'Division' or 'Department' is set, then contributors__institution should be set to "University of Oxford"
institution_identifier = IGNORE for this release
division = Department Affiliation (Generic06)
department =  Primary group descriptor
sub_department =  Sub Unit Affiliation (Generic07)
sub_unit = Generated by ORA review action
research_group = Generated by ORA review action
oxford_college = College Affiliation (Generic03)

**Comment by tomwrobel** [comment]
@jjpartridge is there any action we need to take with regards to this ticket? If so, how would you like to test?

**Comment by jjpartridge** [comment]
@tomwrobel @mrdsaunders Hi Tom, the action here is on Dave until we get to testing to ensure that this data is being sent to us.

**Comment by mrdsaunders** [comment]
@tomwrobel so given time constraints during this week's testing window these will have to fail testing Tom, and I'll try to update during debugging next week.

**Comment by mrdsaunders** [comment]
Part (but not all) of the initial fail in testing is actually incorrect config in QA - `Use object neighbourhood` needs to be set to true. Initial results promising (also relevant to grants data)

![image](https://user-images.githubusercontent.com/11141619/69234038-083d9c00-0b86-11ea-9188-4f172e186f12.png)

**Comment by mrdsaunders** [comment]
The following fields passed initial testing:

- Role (relationship to record)
- Identifiers (Scopus, WoS IDs)
- Family name
- Given name
- Initials
- email address
- ORCID
- SSO
- Division
- Department
- Sub-Department
- College
