### ISSUE TITLE
rioxx file versions not being sent/crosswalked

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#127]
I've just deposited a few files, and I'm not seeing Rioxx file versions being sent any longer, e.g. https://oxris-qa.bsp.ox.ac.uk/viewobject.html?cid=1&id=1011905

**Comment by tomwrobel** [comment]
@mrdsaunders I think I've fixed this with  https://github.com/tomwrobel/ora_data_model/commit/9ee1e706874c1f0c44ed9b47ef322ba964eba7fb

Please have a look and test

**Comment by mrdsaunders** [comment]
Yes test OK:
```
<ora:repository_file xmlns:ora="http://ora/terms/">
      <dc:title xmlns:dc="http://purl.org/dc/elements/1.1/">test-file-1.pdf</dc:title>
      <rioxxterms:version xmlns:rioxxterms="http://www.rioxx.net/schema/v2.0/rioxx/">AM</rioxxterms:version>
```
