### ISSUE TITLE
Empty <mods:location> where has_public_url expected

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#132]
The mapping document maps:

`<symplectic_field name="public-url"><ora_field>has_public_url</ora_field></symplectic_field>`

Crosswalk:
```
<xwalk:field-mapping to="public-url">
        <xwalk:field-source from="location/url"/>
      </xwalk:field-mapping>
```

However, for a live object, `mods:location/mods:url` is unexpectedly empty. I would have expected the ORA url there.

e.g.
`https://oxris-qa.bsp.ox.ac.uk/viewobject.html?cid=1&id=638695`
 `uuid_770dfe71-b153-47e5-ac4d-84a43fcca68b`

**Comment by tomwrobel** [comment]
Confirmed error. An empty mods:location will be sent if there is no value in has_public_url (I assume this isn't a problem).

The value is not being set on migration: issue being tracked in https://trello.com/c/ASa4I872

**Comment by tomwrobel** [comment]
Fixed in https://trello.com/c/ASa4I872 and will be resolved in a remigration shortly. I'm leaving this ticket open until the ticket clears QA and we re-migrate 770dfe71-b153-47e5-ac4d-84a43fcca68b

**Comment by tomwrobel** [comment]
Fixed and closing
