### ISSUE TITLE
What should we do with null SE types (and other?)

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#133]
At present, if no type of work is set, Sword2 will save a work as the first available item type (Book, in alphabetical order).

Is this acceptable behaviour. If not, what would you want it saved as? UniversalTestObject is a possibility

- [x] thoughts from @mrdsaunders 
- [ ] thoughts from @jjpartridge

**Comment by jjpartridge** [comment]
@tomwrobel - our default in migration for 'general item' and for Symplectic item type 'Other' is "Record" so we should probably stay consistent and go with 'Record' which is very close to Universal Test Object anyway I think.

**Comment by mrdsaunders** [comment]
Perhaps we need to distinguish between SE type 'Other' and a type which is genuinely other in the sense of not being in the value map for SE values.   Also it might be helpful to distinguish  genuine test objects.

Having said that it should not happen (only when we deposit a type not known to ORA)

At present the deposit crosswalk value map will ignore values not in the mapping form known SE values. I have tested and it sends them therefore without a 'type_of_work' value.

Could you create a new 'unknown' type? Alternatively what about working with null types?

**Comment by tomwrobel** [comment]
@jjpartridge please note that as 'Record' has never been created as an ORA work type, we'll have to use UniversalTestObject. These can be converted to Records once https://trello.com/c/vl94Tpjj/ is complete

**Comment by tomwrobel** [comment]
@mrdsaunders No, we can't create a new 'unknown' work type at this stage :) It can be a post-release concept if you like, but we don't have time.

If you set field:type_of_work to 'Unknown' that will give us something to detect in Hyrax

**Comment by tomwrobel** [comment]
Note that the code has been updated to save as UniversalTestObject. 

@jjpartridge @mrdsaunders if you're happy with this for the time being, then move this ticket to post release development

**Comment by mrdsaunders** [comment]
Shall I change the crosswalk to set types not recognised to:

<mods:genre type="type_of_work">Unknown</mods:genre>

**Comment by jjpartridge** [comment]
@tomwrobel I am happy with it being set as UTO until the work can be done to set to record (as indictaed at: https://trello.com/c/vl94Tpjj). Can you confirm that this has been done for migrated objects also?

**Comment by tomwrobel** [comment]
@jjpartridge same behaviour (app/workers/object_migration_worker l41) the work will be saved as a universal test object with type_of_work set to 'Record'. That way we can find them later.

@mrdsaunders yes, type_of_work Unknown is fine. That way we can find them later

**Comment by mrdsaunders** [comment]
Crosswalk updated.
