### ISSUE TITLE
Harvest: additional subtypes for Journal articles

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#134]
I've noticed that not all ORA subtypes are configured in SE or included in the harvest subtype value-map. Could someone let me know what subtypes are needed for journal articles please? The list I inherited is:

```
</xwalk:value-map>
      <xwalk:value-map name="types">
      <xwalk:value-mapping from="Editorial" to="Editorial Comment"/>
      <xwalk:value-mapping from="Review" to="Review"/>
      <xwalk:value-mapping from="Correspondence" to="Rapid communication"/>
      <xwalk:value-mapping from="Addendum" to="Addendum"/>
      <xwalk:value-mapping from="Corrigendum" to="Corrigendum"/>
      <xwalk:value-mapping from="Letter" to="Letter"/>
      <xwalk:otherwise-mapping action="ignore-this-value"/>
    </xwalk:value-map>
```
For journal articles, is there anything to add from the [.yml](https://gitlab.bodleian.ox.ac.uk/ORA4/reviewinterface/blob/master/config/authorities/subtypes.yml) other than Erratum? Comment possibly?

Longer term will add for other types, but not a priority for ORA4 testing.

**Comment by mrdsaunders** [comment]
Longer term will add for other types, but not a priority for ORA4 testing.

**Comment by jjpartridge** [comment]
terms:
  - id: Editorial
    term: Editorial
  - id: Review
    term: Review
  - id: Correspondence
    term: Correspondence
  - id: Comment
    term: Comment
  - id: Addendum
    term: Addendum
  - id: Corrigendum
    term: Corrigendum
  - id: Erratum
    term: Erratum
  - id: Abstract
    term: Abstract 
  - id: Letter
    term: Letter

**Comment by mrdsaunders** [comment]
Thanks Jason. One for ORA-SE perhaps but we have also had requests for 'frontispiece' and/or 'Inside cover'. Funnily enough the latter came in this morning.

**Comment by jjpartridge** [comment]
@mrdsaunders  are these more commonly associated with books or journal articles?

**Comment by tomwrobel** [comment]
Frontispiece and inside cover are book properties, not journal articles, thank goodness. We can assign them as subtypes if you like. I don't think that we handle subtypes differently in ORA forms, do we?

**Comment by mrdsaunders** [comment]
OK. For type `Journal Article` I will add `Erratum`, `Abstract` and `Comment` to SE config and the crosswalks.

**Comment by jjpartridge** [comment]
Nope it's fairly straighforward to add more sub-types and these can be added to 'book' if needed. It's just adding to the yml file. The 'trickier' part is the work you will need to do in the crosswalk to send and receive them.

**Comment by mrdsaunders** [comment]
Can I confirm that `comment` is distinct form `editorial comment` (which -> `Editorial` in deposit crosswalk)?

**Comment by mrdsaunders** [comment]
Agreed at ORA-SE 21/11/19. They are distinct. Will update crosswalks and SE `types` field.
