### ISSUE TITLE
Ensure correct header is used for Hyrax work types

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#136]
In issue #51 I specified that the type of work should be provided by the Hyrax-Work-Type header.

This was an error. We've got away with it so far because the code ALSO uses the mods:genre to set work type, which was always set. However, I managed to find an edge case where mods:genre wasn't set, or was set to a different but valid value to Hyrax Work Type (some of the proposed solutions for Record), and everything went wrong.

The CORRECT header, as specified in the documentation, is [Hyrax-Work-Model](https://github.com/CottageLabs/willow_sword/wiki/Headers-used-by-Sword)

Therefore, all references to Hyrax-Work-Type header should be changed to Hyrax-Work-Model. I've updated the Symplectic field mapping and the outbound crosswalk. If anyone can think of anywhere this needs to be fixed, please let me know.

**Comment by tomwrobel** [comment]
@mrdsaunders I've updated the crosswalks in Git and on oxris-qa. If there's no-where else this needs to be updated, please go ahead and close the ticket

**Comment by mrdsaunders** [comment]
Hi Tom I've got some uncommited changes on a local copy (not checked out on a branch). What's the best way to merge - you to tell me what changes you made and I will add to my local and commit?

**Comment by mrdsaunders** [comment]
Is it literally: `all references to Hyrax-Work-Type header should be changed to Hyrax-Work-Model`.

**Comment by tomwrobel** [comment]
yes, but with changelogs

are you using a new branch or master?

**Comment by tomwrobel** [comment]
if you're using a new branch, then you can update after a local commit by

```
git checkout master
git pull origin master
git checkout <my branch name>
git merge master
```

**Comment by mrdsaunders** [comment]
I've updated my local doc form your committed changes. Probably the safest way to do it.
