### ISSUE TITLE
Conference item: name-of-conference, location (confernece place), start-date, finish-date, journal (procedings)

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#139]
uuid_9a077c9e-ce1c-47ce-9e79-bbf6b28199fe / 1012108

#140 is enough to be causing this without further crosswalking issues. Please retest once https://trello.com/c/Zmy1x8c1 passes QA

**Comment by tomwrobel** [comment]
Almost certainly fixed in [TW-fix-compositions c3955263] Add events to base indexer

Will retest once that code is deployed.

**Comment by tomwrobel** [comment]
@tobypitts ready for qa

**Comment by tobypitts** [comment]
@mrdsaunders @tomwrobel I have retested with Pubs: 1012288/  uuid_eb7f3a8c-47fa-45e3-ab4d-6101d2700b41 

[x] name-of-conference  is being displayed in forms 
[x] location is being displayed in forms 
[x] start-date is being displayed in forms 
[x] finish-date is being displayed in forms 

[] journal/ proceedings is not being displayed in forms

**Comment by tomwrobel** [comment]
@tobypitts looking at 

https://ora4-qa-symp.bodleian.ox.ac.uk/concern/conference_items/uuid_eb7f3a8c-47fa-45e3-ab4d-6101d2700b41/

The proceedings are present in the object display page, but there's no field in

https://ora4-qa-symp.bodleian.ox.ac.uk/concern/conference_items/uuid_eb7f3a8c-47fa-45e3-ab4d-6101d2700b41/edit?locale=en

I think this is a form bug only. As such, please raise in the Pre-Go-Live board. I'm closing here otherwise

**Comment by tomwrobel** [comment]
@tobypitts leaving open until you confirm. I think the correct values are crosswalking in both directions and this is a form bug, but I'll wait for your confirmation

**Comment by tomwrobel** [comment]
Hyrax bug only, closing

**Comment by tobypitts** [comment]
Tracked at: https://trello.com/c/M6gebEtD
