### ISSUE TITLE
In progress header

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#14]
Dear Andrew

During the initial discussion process regarding Repotool2, we discussed the use of an 'in progress' HTTP header. This header would be set to true during deposit and used to indicate that Symplectic/Repotool2 was still in the process of depositing a record (and that ORA should take no action until the deposit was completed).

The in progress header would be set to false for the final call Symplectic/Repotool2 made in deposit (presumably the creation of binary file metadata for the final file). This could then trigger further actions within the ORA system.

Are we still planning to use this header?

**Comment by AndrewBennet** [comment]
Hi Tom,

Yes, I am still planning on using that header to allow us to upload the metadata and files separately without "finalising" the item. The final API call will set the In-Progress to false.

Is this still OK on your end?

**Comment by tomwrobel** [comment]
@anusharanganathan I think we're reading this header but not doing anything with it, is that correct?

If so, I'll spec out what should be done when in_progress is set to false.

**Comment by anusharanganathan** [comment]
- [ ] Create a in-progress field in ORA model 
- [ ] Set this to false

**Comment by tomwrobel** [comment]
@anusharanganathan the field to be set is deposit_in_progress in admin_info

This was already created, I simply forgot we'd done it :(

**Comment by tomwrobel** [comment]
reopening because I'm an idiot, it should go into requires_review. @tomwrobel to fix

**Comment by tomwrobel** [comment]
@anusharanganathan I've added a PR: this was working for objects, but not for filesets.

Given that the workflow was:

- create object with metadata (in progress = true)
- create fileset with binary file (in progress = true)
- add binary file metadata to that fileset (in progress = false)

The requires_review flag was not updating.

I've updated the code to add a function to the create_fileset and update_fileset methods, can you take a look?

**Comment by tomwrobel** [comment]
@AndrewBennet tested and working! Closing
