### ISSUE TITLE
Journal Article - event fields: location, start-date, finish-date not showing in forms

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#140]
uuid_06a27c8c-bb1d-40f8-adfd-a0762c38d6cb / 1012115

- [x] event_start_date (verified in 1012213) - fixed in [TW-fix-compositions c3955263] Add events to base indexer
- [x] event_end_date (verified in 1012213) - fixed in [TW-fix-compositions c3955263] Add events to base indexer
- [x] event_location: @jjpartridge @mrdsaunders @tobypitts what field should this be in the Oxris form?

All Hyrax related issues tracked in https://trello.com/c/Zmy1x8c1
Event start date and event end date issues related to: #139

**Comment by tomwrobel** [comment]
Steps:

- Generated a sample crosswalk output in Oxris-QA (see below)
- Pasted that output into Postman sword input
- Saved that output as new Hyrax record in ora4-qa-symp
- Viewed that record in ora4-qa-symp

The values crosswalk correctly

**Comment by tomwrobel** [comment]
Trying to replicate with new object.

- Created: 1012213
  Added: country: test event location value, start date: 2019-11-01, finish date: 2019-11-03
- Visible in crosswalk test output: start date and finish date 
- Not visible in crosswalk test output: country (not sure if this is an error)
- File deposited
- ORA record created uuid_1456dc40-6261-4533-9f8a-de8cfe3598d7: event start date and event end date crosswalk correctly.

**Comment by tomwrobel** [comment]
SOLUTION: Once an object was moved to review, the event information was not being sent. Once the object was sent back from review, it was sent without event information (lost in transit)

That should now be fixed: [TW-fix-compositions c3955263] Add events to base indexer

**Comment by tomwrobel** [comment]
@tobypitts ready for QA

**Comment by tobypitts** [comment]
@mrdsaunders @tomwrobel I have retested with Pubs: 1012287/ uuid_4ed802ed-48c9-4bee-ace7-e24772d47b06

- [x] start-date can be read in Review forms correctly
- [x] finish-date can also be read 

- [ ]Location- from SE 'Country' is not being read

**Comment by tobypitts** [comment]
citation place of publication has been read in forms correctly for  1012289 uuid_3dbec05d-e3ce-42b4-b939-d7504386bf16
