### ISSUE TITLE
c-apc field not reading in forms 

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#141]
uuid_9a077c9e-ce1c-47ce-9e79-bbf6b28199fe / 1012108

**Comment by tomwrobel** [comment]
@tobypitts that item appears fine in Symp and in Review. Can you retest with a different object?

**Comment by tomwrobel** [comment]
@tobypitts bumping

**Comment by tobypitts** [comment]
@tomwrobel uuid_1085389c-60cb-44c4-beff-ccf6c2c67867 failing in forms. Shall I add to trello?

**Comment by tomwrobel** [comment]
@tobypitts the issue is that the value is being sent by SE as "Yes" and "No" not "yes" and "no"

@mrdsaunders how to fix?

**Comment by mrdsaunders** [comment]
I have amended the crosswalk to use a value map to change case. Toby and I will retest.

**Comment by tobypitts** [comment]
@tomwrobel @mrdsaunders I'm happy that this is now reading in forms (test object was 1012477- See line 193 of RT2 spreadsheet)
