### ISSUE TITLE
Embargo comment on deposit

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#148]
Data added by the depositor on deposit seems to be crosswalking as evidenced by Sword call (although Toby will be checking forms).

However, small point - I notice that 'Automatically set by Sword2' is being appended to the   <ora:embargoComment>.

Not sure if this is intended behaviour.
```
<ora:repository_file xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:rioxxterms="http://www.rioxx.net/schema/v2.0/rioxx/" xmlns:foxml="info:fedora/fedora-system:def/foxml#" xmlns:oxds="http://vocab.ox.ac.uk/dataset/schema#" xmlns:ora="http://ora.ox.ac.uk/terms/" xmlns:symp="http://symplectic/symplectic-elements:def/model#" xmlns:ali="http://www.niso.org/schemas/ali/1.0/">
                    <dc:title>Test deposit.pdf</dc:title>
                    <dcterms:hasVersion/>
                    <rioxxterms:version>VoR</rioxxterms:version>
                    <oxds:embargoedUntil>9999-12-31</oxds:embargoedUntil>
                    <ora:embargoComment>Test embargo commentsAutomatically set by Sword2</ora:embargoComment>
                    <ora:embargoPeriod>18 months</ora:embargoPeriod>
                    <ora:embargoReleaseMethod>Check back</ora:embargoReleaseMethod>
                    <ora:filesetId>sympn870zq800</ora:filesetId>
</ora:repository_file>
```

**Comment by tomwrobel** [comment]
Verified. will fix

**Comment by tomwrobel** [comment]
@jjpartridge The issue is that the embargo end date is being set automatically, and that's what we need to append. I'm changing the comment to add 'Embargo end date automatically set by Sword2'.

Is this acceptable as a solution?

**Comment by tomwrobel** [comment]
[feature/ora_customizations 8118315] Fix embargo comment on deposit

**Comment by jjpartridge** [comment]
@tomwrobel Yes this sounds fine to me - good to be clear where the date came from.

**Comment by mrdsaunders** [comment]
Looks fixed to me
```<ora:embargoComment>test_comment_ds. Embargo end date automatically set by Sword2</ora:embargoComment>```
