### ISSUE TITLE
SE author-licence

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#149]
Mapping document has:

`<symplectic_field name="author-licence"><ora_field>licence</ora_field></symplectic_field>`
`<symplectic_field name="publisher-licence"><ora_field>licence</ora_field></symplectic_field>`

SE `author-licence' is a reserved field in SE.

I propose that on deposit:
`<symplectic_field name="publisher-licence"><ora_field>licence</ora_field></symplectic_field>`

On Harvest
<No mapping>

**Comment by tomwrobel** [comment]
I'm happy with that, you're the expert on SE values!

**Comment by mrdsaunders** [comment]
Should read:
On Harvest - no mapping

**Comment by tomwrobel** [comment]
@jjpartridge are you happy with this?

**Comment by tomwrobel** [comment]
@jjpartridge bumping

**Comment by jjpartridge** [comment]
@tomwrobel absolutely we don't care about the author licence this is checked as part of the review process (as it is rarely correct!)

**Comment by mrdsaunders** [comment]
Done
