### ISSUE TITLE
Repotool2 discovery and read of previously deposited objects

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#15]
Hi Andrew

This question came up in deployment discussions today.

Currently, the link between a Symplectic record and an ORA record is maintained by the use of 'signpost' objects in Fedora3/Repotool 1. 

In Repotool2, this link is maintained by the Repotool2 system.

However, is the Repotool2 able to discover a link between a Symplectic Record and an ORA record that was deposited using Repotool 1? We don't want to lose connection between our existing objects.

**Comment by AndrewBennet** [comment]
Hi Tom,

Good question! We have developed a tool which can be provided a CSV file containing pairs of Elements publication IDs and the RT2 source record IDs. This tool can be run against the Elements database to register the desired associations. When the RT2 items are subsequently harvested in, Elements will ensure that they are brought into the specified Elements publications. This step will have to be performed after the upgrade of Elements, but before the connection to the new RT2 source.

Cheers,
Andrew

**Comment by tomwrobel** [comment]
Understood. I'll add that to the deployment list!

**Comment by tomwrobel** [comment]
@AndrewBennet Sorry to re-open but two questions occurred: 

- how long should we allow for this process to take in Oxris (Oxford Symplectic Elements)? Obviously we'll need to plan some downtime
- can this process be done via the interface, or will it need server access? If it's the latter, we have an extra set of people who will need to be involved in deployment

**Comment by AndrewBennet** [comment]
From experience running the tool on a production-sized database, I've seen the tool take ~10 minutes or so. I would perhaps allow an hour, just to be safe.

The tool cannot be run via the UI - it is a standalone executable which must be run directly on the application server.

**Comment by tomwrobel** [comment]
Brilliant, many thanks.

Closing.
