### ISSUE TITLE
ORA field physical_form changing position in Sword output

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#154]
e.g. `1012409`

In the SE test METS it outputs as:
```
<mods:physicalDescription>
	<mods:form type="physical_form">physical_form test</mods:form>
</mods:physicalDescription>
```
...which seems to be correct from the `ora_datamodel_to_mets-2-1.xml` document.

However in the Sword output (`uuid_80bdaf8b-1920-45f6-8c48-72884aa4fe3c`) it seems to have changed 'position' to a different node in the xml:
```
<mods:originInfo>
	<mods:form type="physical_form">physical_form test</mods:form>
</mods:originInfo>
```
...and hence is not harvesting.

**Comment by tomwrobel** [comment]
Fixed in [feature/ora_customizations 6571a0c] Output physicalDescription fields in correct MODS element

**Comment by tomwrobel** [comment]
please retest and clsoe

**Comment by mrdsaunders** [comment]
Tested and passed object `1012413`
