### ISSUE TITLE
SE Subtitle < - > ORA alternative_title mapping

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#155]
I had mapped SE `field-47` (subtitle) to ORA `alternative_title` based on Jason's suggestion on the '[Underlying fields](https://unioxfordnexus-my.sharepoint.com/:x:/r/personal/bodl1072_ox_ac_uk/_layouts/15/Doc.aspx?sourcedoc=%7B1D2C3E13-6BCF-41A7-8505-847B4D6744F5%7D&file=UnderlyingFields_Publication_20190805.xlsx&action=default&mobileredirect=true&cid=91e3e64a-1151-4edb-99bb-3c4e4753f5d2)' document.

However they are not actually in the mapping document and apparently one of the reviewers raised this today.

Should we formally add:
`<symplectic_field name="field-47"><ora_field>alternative_title</ora_field></symplectic_field>` to the mapping document?

**Comment by jjpartridge** [comment]
@mrdsaunders sounds sensible to me - if you are collecting subtitle (field-47) then we should accept it - especially for books and book sections. 
Thanks

**Comment by mrdsaunders** [comment]
Thanks Jason. Done.
