### ISSUE TITLE
Correct public URL not being set in ORA

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#156]
Public URL is coming through to SE just as as `https://ora.ox.ac.uk/objects/`

This is an ORA Hyrax bug: harvesting is correct. Publication is setting the wrong value for the object, see: 

https://trello.com/c/ATTa1jOT

**Comment by tobypitts** [comment]
Retested uuid_5f63ea60-8156-43df-ac72-6ab0a627fcf6. Happy that this has now passed. 
![image](https://user-images.githubusercontent.com/49687038/70896263-5066a780-1fe8-11ea-94ea-32f2f9011a7c.png)
 Closing
