### ISSUE TITLE
Production date for device/product does not display in ORA4 forms

### ISSUE THREAD

**Issue by tobypitts** [tomwrobel/ora_data_model#158]
[From https://trello.com/c/RISeaQEA]

Production date in Oxris displays as 'publication date' in ORA4 preview view but does not display in the form view. Xwalk back from ORA shows 'production date as' 01_12_2019 (see screenshots below)
 
![image](https://user-images.githubusercontent.com/49687038/70993115-36e65e00-20c3-11ea-911a-4fb70c132c3f.png)

![image](https://user-images.githubusercontent.com/49687038/70993123-3a79e500-20c3-11ea-98bd-ca77a18ff7bd.png)

![image](https://user-images.githubusercontent.com/49687038/70993131-3e0d6c00-20c3-11ea-9cc6-72cf89babb67.png)

@tomwrobel "looks like a crosswalk issue. dateIssued is actually citation_publication_date, which is what is being saved and displayed

The value should be set and sent at <mods:dateOther type="production_date" encoding="iso8601">field:production_date</mods:dateOther>"

**Comment by tobypitts** [comment]
@mrdsaunders Will need to retest this when SE QA is available again

**Comment by tomwrobel** [comment]
I don't think we were ever reading the value: [feature/ora_customizations 0a2b415] Read production date has an addition to read production_date from the METS. I'll deploy

**Comment by tomwrobel** [comment]
note, this hasn't fixed it. I'll need to work on this a little longer, but please do create a test item

**Comment by tomwrobel** [comment]
[feature/ora_customizations dc61843] Put production date in the right place in outbound crosswalk

**Comment by tomwrobel** [comment]
@tobypitts fixed in inbound and outbound willow sword, please re-test

**Comment by tomwrobel** [comment]
@mrdsaunders I've got this to deposit cleanly, but the new production date isn't being read by the harvest crosswalk. See https://oxris-qa.bsp.ox.ac.uk/viewobject.html?cid=1&id=1077942, for which the production date is December 2 in Sword: https://ora4-qa-symp.bodleian.ox.ac.uk/sword/collections/default/works/uuid_ff8f3a18-9ddb-46f3-831a-5b99dce85291

**Comment by mrdsaunders** [comment]
Hi Tom. I believe this is because that date is only harvested to SE `publication-date` where sub-type = Product.

**Comment by tomwrobel** [comment]
@mrdsaunders does that mean that sub-type is not being set in the outbound crosswalks?

**Comment by mrdsaunders** [comment]
No it is, from product/device

Sent from my iPhone

On 19 Dec 2019, at 13:19, Tom Wrobel <notifications@github.com> wrote:

﻿

@mrdsaunders<https://github.com/mrdsaunders> does that mean that sub-type is not being set in the outbound crosswalks?

**Comment by tomwrobel** [comment]
Sub type of work isn't being set in the outbound crosswalk output for 1077942. mods:genre@type="type_of_work" is set, but  mods:genre@type="sub_type_of_work" is not being provided.

**Comment by mrdsaunders** [comment]
Good spot Tom, as this is an unresolved issue. It was left because there is an ambiguity -  should SE `Device/Product` map to subtype `Device` or `Product`? I suspect we will have to choose one or the other. Propose `Product`?

**Comment by tomwrobel** [comment]
one for @jjpartridge in the new year I think!

**Comment by jjpartridge** [comment]
@mrdsaunders @tomwrobel @tobypitts coming to this late.

We created the sub-types to account for the item types in SE. If they are a single type in SE then lets just change the subtype yml list in ORA4 and make it the same - i.e. Device/Product. 

It is extremely unlikely that we will be creating this type or work any other way than via SE to apply a distinction. 

ACTION: update https://gitlab.bodleian.ox.ac.uk/ORA4/reviewinterface/blob/master/config/authorities/subtypes_physicalobject.yml  
FROM
terms:
  - id: Artifact
    term: Artifact
  - id: Device
    term: Device
  - id: Product
    term: Product
TO
terms:
  - id: Artifact
    term: Artifact
  - id: Device/Product
    term: Device/Product

**Comment by tomwrobel** [comment]
@jjpartridge This will go into post-release development. Shall we make them products for now, and then create a post-go-live ticket to change the subtypes. I say this because we've got enough model changes for now :)

**Comment by jjpartridge** [comment]
@tomwrobel Is it a model change - it is just updating the drop-down choice for the field right?

**Comment by tomwrobel** [comment]
@jjpartridge ah, so it's just a subtype?

In that case, then no worries. Create a trello ticket for it and we can get this done cleanly

**Comment by jjpartridge** [comment]
@tomwrobel see https://trello.com/c/IM7P2awz

**Comment by tomwrobel** [comment]
[TW-clean-up-product-subtypes 6dbc2d46] Bring physical item subtypes in line with Oxris

https://gitlab.bodleian.ox.ac.uk/ORA4/reviewinterface/merge_requests/207

**Comment by mrdsaunders** [comment]
- [ ] @jjpartridge to confirm interim mapping of SE type: Device/Product -> ORA type: Physical object subtype: Product
- [ ] @jjpartridge or @tomwrobel  confirm this is post release development and update tag

**Comment by jjpartridge** [comment]
@tomwrobel I'm confused by this haven't you updated the .yml file for the subtype field to show Device/Product?

**Comment by mrdsaunders** [comment]
So its been done and needs testing? (I don't have access to your Trello)

**Comment by tomwrobel** [comment]
@mrdsaunders it has been done and will need testing, but doesn't need to be resolved before harvest, so I'm happy to move to post-release at this stage

**Comment by tomwrobel** [comment]
@tobypitts @mrdsaunders can we get this through testing? I think it's all deployed

**Comment by mrdsaunders** [comment]
QA'd by me and Toby.
