### ISSUE TITLE
Notes field from SE is going to Public record note in ORA4 Form 

### ISSUE THREAD

**Issue by tobypitts** [tomwrobel/ora_data_model#166]
The 'notes' field from an SE deposit is mapping to the public record note field (additional_information) in ORA 4, which then displays in public. This information should be mapping to the ORA field deposit_note instead. 

@mrdsaunders This should be resolved before GO LIVE if possible, and can be done in QA and then deployed.

Example object on QA: 
Pubs:1078101
uuid_8722344c-862e-441f-b909-a1cc06ddf007

Please note that the original instruction in the Sympectic Mapping file is to additional_information, this was correct, but is now incorrect.

To close:

- [ ] amend Symplectic to ORA field mapping file to map notes to deposit_note
- [ ] amend crosswalks accordingly

**Comment by mrdsaunders** [comment]
Updated harvest and deposit. QA'd harvest with uuid_041e1519-ee55-4f84-bb85-9085f7aba43a

**Comment by tomwrobel** [comment]
@tobypitts if you're happy, then let's merge and close

**Comment by tobypitts** [comment]
@tomwrobel @mrdsaunders yep I'm happy. looks good. Thank you both
