### ISSUE TITLE
Provide Symplectic Ltd with crosswalk samples 

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#169]
In order to develop the crosswalk engine further, Symplectic Ltd (via @AndrewBennet) have requested some sample data of Oxris records and ORA Sword2 responses that are particularly unpleasant.

When we developed the initial crosswalk engine, we allowed Symplectic Ltd to take a copy of our production data and build their own machine, and connected that machine to an ORA4 dev box for testing.

@AndrewBennet do you want to do this again? We'd need:

- [ ] license agreements (could we extend the existing one?)
- [ ] to agree server and config settings
- [ ] an ORA4 dev box as a target

Alternatively, we could simply agree on a set of test objects and create them here?

@mrdsaunders  thoughts?

**Comment by AndrewBennet** [comment]
Hi @tomwrobel 

A set of test objects would be sufficient - would be able to pass over XML documents for some of the larger / more complex items? I can simply run comparisons between what is produced using Elements v5.19 and v5.20, using the xwalk map file in this repository.

Thanks,
Andrew

**Comment by tomwrobel** [comment]
done, in sample_sword_objects
