### ISSUE TITLE
ORA: contributors__display_name

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#17]
The ORA field contributors__display_name should be populated from Symplectic fields last-name and first-names, in the format "{first-names} {last-name}". This is in addition to the 1-1 mappings for these fields to contributors__family_name and contributors__given_names respectively

**Comment by AndrewBennet** [comment]
Xwalk map file adjusted to use the format `person:firstnames-lastname` (instead of `person:lastname-firstname`)
