### ISSUE TITLE
Embargo end data and excessive embargo calculation

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#173]
Scenario:
An embargo end date is entered which is the same day as publication date but in the following year (e.g. 1 Jun 2018 -> 1 June 2019)
Max embargo is set in SE as 365 days

Outcome:
OA Monitor calculates as non compliant for excessive embargo. If max embargo is set to 366 days it is calculated as compliant for embargo length.

Prior to considering adjusting the OAM maximum embargo policy setting to accommodate this, can someone confirm that this method of entering embargo end date is used consistently by reviewers?

**Comment by tomwrobel** [comment]
@jjpartridge this is one for you as it relates to reviewer practice.

My understanding is that an ORA embargo end date is the date on which a file can be released, but that OA Monitor defines it as the last date on which an embargo would be effective.

That is, in ORA an embargo end date of 2020-02-20 would mean a file could go live on 2020-02-20, to OA Monitor, that would mean a file could go live on 2020-02-21.

**Comment by jjpartridge** [comment]
I believe that this was talked through yesterday with Toby. Yes. this is how it has been calculated in the Access Database and in ORA4. 

It is also how Reviewers work to apply the date - e.g. publication date 02/01/2019, embargo of 12 months, embargo end date 02/01/2020.

**Comment by mrdsaunders** [comment]
Thanks, this means we can (robustly) update max embargo in OAM policy settings to 366/732.

**Comment by mrdsaunders** [comment]
Done
