### ISSUE TITLE
Configure a deposit licence for ORA in Oxris Production (or QA)

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#176]
Currently, there is no deposit licence configured for ORA in Oxris Production. I'm pretty sure this is true for QA as well.

Consequently, new deposits are not technically subject to the licence agreement (we can probably use implied consent for the old ones, but...)

A deposit licence needs to be added to https://oxris.ox.ac.uk/rt2licences.html?sid=29 (and to the equivalent page on QA)

This licence should have the following values:

Licence file: can be uploaded from https://ora.ox.ac.uk/deposit_agreements/v5
Licence identifier: https://ora.ox.ac.uk/deposit_agreements/v5
Licence display name: ORA Deposit Licence

One for @mrdsaunders or @eugeniobarrio to complete (I think)

**Comment by mrdsaunders** [comment]
Enabled in QA and PROD.
