### ISSUE TITLE
Ensure Sword2 file_version mappings are case insensitive

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#179]
At present, willow_sword will auto-populate the file_version field for a fileset IF file_rioxx_file_version is set. However, this is dependent on a mapping.

This mapping expects file versions in UPPERCASE, whereas they are sent in title case by Oxris.

**Comment by tomwrobel** [comment]
@mrdsaunders please retest in QA, change deployed

Deposit a file with VoR as the rioxx version. The file version should be Version of record

**Comment by mrdsaunders** [comment]
Have done for 1086495

**Comment by tomwrobel** [comment]
That's a pass.
