### ISSUE TITLE
Article number

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#18]
If an article number begins with the text "ARTN", this should be removed, leading 0s should also be stripped

**Comment by AndrewBennet** [comment]
👍 Sure thing. The crosswalk engine supports regex matching and replacing, so this can be done.

Will you only want to crosswalk numerical article numbers? If so, a regex like: `^(?:ARTN ?)?(?:0+)(\d+?)$` would match these strings, and the first capture group (the numerical part without leading 0s) could be used as the crosswalked value.

**Comment by tomwrobel** [comment]
There are non-numerical numbers?
If it doesn't match the regex, I'd be happy with a straight reproduction of the value. We can always tweak if its an issue!

Close when you're ready to :)

**Comment by AndrewBennet** [comment]
The Elements field (`number`) has an underlying type of just `Text` (I've seen data sources provide values like `ARTN 071504` and  `ARTN 45LT01`). I can easily make it strip off `ARTN` regardless of whether the following part is numerical, if that would be suitable?

**Comment by tomwrobel** [comment]
Yup, that sounds good
