### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#19]
If the pagination is a range, then it should be given with a hyphen between the start and end pages.
If the pagination is a count, then the text " pages" should be added to the value, e.g. 

```
      <api:field name="pagination" type="pagination" display-name="Pagination">
        <api:pagination>
          <api:page-count>32</api:page-count>
        </api:pagination>
      </api:field>
```

becomes

```
                            <mods:extent unit="pages">
                                <mods:list>32 pages</mods:list>
                            </mods:extent>
```

**Comment by AndrewBennet** [comment]
Sometimes the pagination field in Elements contains both a range _and_ a count. What should be done in that case? Just use the range? Or use "1-12 (11 pages)", or similar?

**Comment by tomwrobel** [comment]
Just the range please! I hope our users can count...
