### ISSUE TITLE
Review status

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#2]
In order for us to map our review status to the Symplectic review status, we need to compile a list of Symplectic review statuses. We can then use value mappings to crosswalk this. 

I assume the Symplectic Elements review statuses are (as fed into OAM): 

- Not deposited
- Unknown
- Deposit incomplete
- In review
- Live
- Withdrawn
- Deposited (not live)
- Deleted

Once these are confirmed we'll work out what our mappings need to be!

**Comment by AndrewBennet** [comment]
In the RT2 world, the available statuses are:

- Unknown
- Deleted
- Private
- Private (in preparation)
- Private (in review)
- Private (withdrawn)
- Public

Some notes on these:

`Unknown` should be avoided in general - it is actually not used by any of our existing RT2 integrations.
`Deleted` should not be set manually - it is the status assigned when a repository item can no longer be found (with a 404 error, for example).
`Private` exists only to support cases where we cannot distinguish between the more fine-grained private statuses of `In Review`, `In Preparation` and `Withdrawn`.

Not all the statuses need to be mapped to. Our DSpace integration, for example, only maps to `Withdrawn`, `Public` and `Private`. Our EPrints integration, on the other hand, does allow us to support `Private In Review` and `Private Withdrawn` also.

**Comment by tomwrobel** [comment]
@jjpartridge can you suggest how these values would map to ORA fields. I believe you have some questions?

**Comment by tomwrobel** [comment]
ORA statues to map?

- Deposited: Private
  - the item has been deposited and received by ORA, AND
  - the item has not been claimed or reviewed
- In Review: Private (in review)
  - the item has been deposited and received by ORA, AND
  - the item has been claimed, or is referred, escalated, approved
- Public: Public
  - the item has been deposited and received by ORA, AND
  - the item has been approved by reviewers for publication (subject to embargo periods)
  - the item has been published

**Comment by jjpartridge** [comment]
@AndrewBennet forgive my RT2 world ignorance, how do the current status values in SE (RT1) relate to the RT2 ones?

Not deposited - Private???
Unknown - Unknown
Deposit incomplete - Private (in preparation)???
In review - Private (in review)
Live - Public
Withdrawn - Private (withdrawn)
Deposited (not live) - ????
Deleted - Deleted

**Comment by AndrewBennet** [comment]
Hi @jjpartridge 

The status display name mappings are as follows:

| RT1 | RT2 |
|------|-----|
| Not deposited | N/A |
| Unknown | Unknown |
| Deposit incomplete | Private (in preparation) |
| In review | Private (in review) |
| Live | Public |
| Withdrawn | Private (withdrawn) |
| Deposited (not live) | Private |
| Deleted | Deleted |

Note that Not Deposited doesn't appear in RT2, since - in RT2 - information about an item in a repository is held in an Elements record, and if there is no repository item, then there will be no record.

**Comment by jjpartridge** [comment]
@AndrewBennet Thanks that's great
@tomwrobel  then as discussed above, so shall it be below!
@eugeniobarrio for info.

| RT1 | RT2 | ORA4 |
|------|-----|-----|
| Not deposited | N/A | N/A |
| Unknown | Unknown | N/A | 
| Deposit incomplete | Private (in preparation) | N/A |
| In review | Private (in review) | In review (as noted in @tomwrobel message above) |
| Live | Public | Public (as noted in @tomwrobel message above) |
| Withdrawn | Private (withdrawn) | N/A |
| Deposited (not live) | Private | Deposited (as noted in @tomwrobel message above) |
| Deleted | Deleted | N/A |

**Comment by tomwrobel** [comment]
@AndrewBennet the final part of this discussion is how we crosswalk these values

As far as I remember, we proposed a new field just for the Symplectic crosswalk: symplectic_review_status

@jjpartridge  given the outcome of this discussion, can we not use the inbound crosswalks to map the ORA field record_review_status? Are there any other status values that might be here that would confuse things?

| RT2 | ORA4 field:symplectic_review_status | ORA4 field: review_status |
|------|-----|-----|
| Private (in review) | Private (in review) | In review |
| Public | Public | Public |
| Private | Private | Deposited |

**Comment by AndrewBennet** [comment]
I may well be forgetting something, but I don't think we'll need a separate symplectic field. We can just map the `review_status` field values to our values. I'm not currently seeing much in the `amdSec` section - is this where it will be located?

**Comment by tomwrobel** [comment]
It will, yes. See https://github.com/tomwrobel/ora_data_model/blob/8e18fd35d0e546456183c6828b70abef89a6519f/ora_datamodel_to_mets-2.0.xml#L662

@jjpartridge once we have a list of values from WeiHsi, we can store them in the inbound crosswalk. For now, all that @AndrewBennet will have to do is take In Review, Public, and Deposited

Yes, there isn't much in the amdSec, but that's becuase the only records there are via Symplectic Elements and most of the values in there relate to metadata that isn't being crosswalked currently :)

**Comment by tomwrobel** [comment]
@AndrewBennet these values do not seem to be displaying correctly in OA monitor or crosswalked into the RT publication page. Have I missed something?

I'm also not clear on how 'Repository Item Status' in OA monitor is being calculated, is this related to it?

**Comment by AndrewBennet** [comment]
I have not yet put in place the mapping from review_status to our repository-status: everything is coming through as Public (hardcoded). I will adjust the xwalk in to fix this.

**Comment by tomwrobel** [comment]
Please map as documented in: https://github.com/tomwrobel/ora_data_model/issues/2#issuecomment-478963073

**Comment by AndrewBennet** [comment]
Change is in place - please re-test.
Note that a lot of the records seem to not have a value for this ORA field so they are coming through as "Unknown" at present

**Comment by tomwrobel** [comment]
I have retested! I realise that a lot of fields don't have any value at all, which is fine (I'll put some default handling for this in https://github.com/tomwrobel/ora_data_model/issues/69).

However, I'm not sure the correct values are moving back and forth for :

| ORA4 value for 'record_review_status' | Expected Symplectic Repository Item Status | Displayed Symplectic Repositoy Item Status | Correct/Incorrect | 
|:----------------------------------:|:----------------------------------:|:---------------------------------:|:-------------------|
| Deposited | Private | Deposit incomplete | **Incorrect?** |
| In review | Private (in review) | In Review | Correct |
| Public | Public | Live | Correct |

**Comment by AndrewBennet** [comment]
Whoops, I was mapping to `Private (in preparation)` instead of just `Private`. I've adjusted this.

**Comment by tomwrobel** [comment]
Done, and tested!

Closing :)

| ORA4 value for 'record_review_status' | Expected Symplectic Repository Item Status | Displayed Symplectic Repositoy Item Status | Correct/Incorrect | 
|:----------------------------------:|:----------------------------------:|:---------------------------------:|:-------------------|
| Deposited | Private | Deposited (not live) | Correct |
| In review | Private (in review) | In Review | Correct |
| Public | Public | Live | Correct |
