### ISSUE TITLE
Peer review status: set from item type?

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#20]
The ORA field peer_review_status doesn't map to existing values in SE. However, it can likely be inferred from item type. Do we want to do this?

**Comment by jjpartridge** [comment]
Se doesn't have peer_review_status. How would you infer and pass this?

**Comment by tomwrobel** [comment]
It would be by assuming that if something is a journal article that it has been peer reviewed. Or it is a type of object that is normally peer reviewed (data sets aren't, for example).

**Comment by tomwrobel** [comment]
@jjpartridge I'm assuming this isn't practical. Shall we close?

**Comment by jjpartridge** [comment]
We could do this based on the presence of an issn which might be a bit more accurate

**Comment by tomwrobel** [comment]
Not accurate enough, we decided. Closing
