### ISSUE TITLE
Contributor_record_identifier

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#3]
In the ORA data model, a grant is linked to a person via an identifier value stored against that person. This is called a contributor_record_identifier, and is in the form "ora_cri_{uuid}", e.g. ora_cri_12345678-1234-1234-1234-12345678abcd.

The contributor record identifier must be generated for each contributor on a record, but it ONLY applies to that contributor within that record (it could even be generated de novo on each object save, if necessary). 

The crosswalk engine would need to generate a 'cri' for each person in the contributors list, and ensure that this was a value attached to any grant that needed to be linked to that person.

**Comment by AndrewBennet** [comment]
Could you clarify where in the output MODS would this generated identifier tag the grant? Would it be somewhere around https://github.com/tomwrobel/ora_data_model/blob/master/ora_datamodel_to_mets-2.0rc5.xml#L367 ?

Generating a UUID is actually not possible _at present_ in the xwalk framework; would it be possible to use a unique (within the document) integer? If not, I will look at ways we could achieve this.

**Comment by tomwrobel** [comment]
It would be at https://github.com/tomwrobel/ora_data_model/blob/master/ora_datamodel_to_mets-2.0rc5.xml#L379, the is_funding_for field(s) would have the value of the contributor__contributor_record_identifier of the person(s) funded.

A unique (within the document) identifier is possible, so long as it's OK that you don't get this identifier back on any return crosswalk activities. 

We would need to build the conversion into the Sword2 <-> Hyrax crosswalk at our end. We'd want it to be a UUID so that we have a chance of (in the future) linking people between records without identifier collision.

If it's an easy thing to add a randomly generated UUID, then that would be great. But if you can't, then we can go with the unique identifier within the document.

**Comment by AndrewBennet** [comment]
Hi Tom -

I'm struggling to fully get to grips with this one. It's possible that this is beyond the capabilities of the RT2 deposit functionality. Let me check. The Elements data model allows links between Publications and Users, Publications and Grants, and Grants and Users. When depositing, only the objects and links directly pointing to the context publication are available. So we cannot look at links of grants which are linked to the deposited publication.

See the attached image:

![img_0894 44039](https://user-images.githubusercontent.com/2078225/53500510-5b286e00-3aa2-11e9-9467-a51c6840eda7.gif)

The arrows represent links and the circles are items in Elements. Only the links and objects within the dashed line are available during the deposit. Does that scupper this plan? Or did you want to link the users linked to the publication to the linked grants?

I hope that makes sense!

**Comment by tomwrobel** [comment]
I think we should be OK. I want to link the grants linked to the publication to the user linked to the publication. The Symplectic Elements person ID that links the Grant at 4 o'clock to the user at 2 o'clock would be sufficient, so long as that value was in the contributor_record_identifier.

So something like:

People:
  - Person1:
    - contributor_record_identifier: person_201
    - pubs_person_id: person_201 

Grant:
 - funder name: Bob
 - grant_identifier: 12345
 - is_funding_for: person_201

Would work.

**Comment by AndrewBennet** [comment]
In this example, we will not be able to see the link between the grant at 4 o'clock and the user at 2 o'clock. What we _could_ do is link the grant at 4 o'clock to _all four_ users linked to the publication (and do the same for the grant at 8 o'clock). Would that work?

[Note to self: label the objects in the diagrams in future!]

**Comment by tomwrobel** [comment]
I don't think that linking to all linked users is necessarily correct: it's not accurate data.

After discussion with @jjpartridge we've decided that we're happy for the time being not to crosswalk the value funders__funder_grant__is_funding_for. 

It'll still be there as a field in the METS if you read the record in ORA, but if you can't supply the value at this point then that's OK for now. 

How much work would it be to make this value available for a future release? It would help our review team, so we would like to be able to access this link/value in the future.

**Comment by AndrewBennet** [comment]
It was a design decision to only include 1 level of linked objects in the API representation to be passed to the crosswalk. In order to crosswalk users linked to grants linked to the publication in question, we would require 2 levels of linked objects to be serialised into XML and crosswalked. This is liable to be very large - if there is a lot of interlinking between publications with large numbers of authors, the input XML document could become huge in size.

As a result, I don't expect us to expose this information in the input to the crosswalk. I will discuss with colleagues whether there is any other approach that could be taken...

**Comment by tomwrobel** [comment]
It's worth a longer term think. A major part of what ORA does is track funder compliance. Anything that makes it simpler for our review team to link these together is very valuable.

Anyhow, we can't fix it for now :) Closing
