### ISSUE TITLE
Summary documentation

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#30]
There has been a change to the structure of the METS files. The field summary_documentation has moved from within the datamodel specific section into a <mods:abstract type="summary_documentation"/> element

**Comment by tomwrobel** [comment]
@anusharanganathan @AndrewBennet When you've read this (and if you understood it), please tick your name off below. We'll then close the ticket

- [ ] Anusha
- [ ] Andrew

**Comment by anusharanganathan** [comment]
Understood @tomwrobel

**Comment by AndrewBennet** [comment]
Understood, but I don't actually see a mapping from an Elements field to summary_documentation - is that right?

**Comment by tomwrobel** [comment]
@AndrewBennet actually, we will be using it for patents, so it is relevant. I've added a mapping to the crosswalk file under abstracts

If you're happy, please close :)

**Comment by AndrewBennet** [comment]
👍 all good
