### ISSUE TITLE
ORA Data Model v2.0

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#32]
Pending any objections, we will be locking (and releasing) the ORA Data Model v2.0 tomorrow (Friday). 

At this point, we will not make any non-backwards-compatible changes to the data model until v3.0, which will not be approached until after ORA4 release.

In expectation of this, I've already updated the crosswalk and sample METS and JSON files.

Individual issues have been set up to document any changes from 2.0rc5. The tickets for this are #29 #30 #31

**Comment by jjpartridge** [comment]
Updated at: https://sharepoint.nexus.ox.ac.uk/FuncReqs

**Comment by jjpartridge** [comment]
Replaced by https://github.com/tomwrobel/ora_data_model/milestone/1
