### ISSUE TITLE
additional_information: appending to a field rather than replacing value

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#37]
Hiya!

We've identified a field that will write into the general ORA 'notes' field ('additional_information'). However, we may well have values already in place from other parts of the crosswalk. Is it possible in the crosswalk to append to a value, rather than to replace it.

Note that I'm updating the crosswalk xml file currently, but the two symplectic fields are notes and (funding) acknowledgement-text

**Comment by AndrewBennet** [comment]
It isn't possible to have two different field mappings "merge" into one in the output. But what we could do instead is define a single mapping which concatenates the various source values together. E.g.

```
<xwalk:field-mapping to="note">
  <xwalk:field-source attribute-name="displayLabel" value="additional_information" />
  <xwalk:field-source concatenate-with-separator="; ">
    <xwalk:field-source from="notes" />
    <xwalk:field-source from="funding-acknowledgements" data-part="funding-acknowledgements:acknowledgement-text" />
  </xwalk:field-source>
</xwalk:field-mapping>
```

**Comment by tomwrobel** [comment]
That's equivalent, so works! Closing
