### ISSUE TITLE
author-url to contributors__contributor_website_url

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#4]
There doesn't seem to be anything to link author-url to a person, but the crosswalk engine would have to add the value to a specific contributor using contributors__contributor_website_url

**Comment by tomwrobel** [comment]
Bumping! Sorry. This keeps coming up in the sample PUBS atom feeds.

**Comment by AndrewBennet** [comment]
I'm not sure that this is the best place for the "author-url" field. That field is, shall we say, one of our older, less-well-defined fields... and what it is actually meant to store is not always clear. I think it stems from Arxiv, where we would consider the URL of the item on Arxiv the "author-url", but the URL of the item in a journal website the "publisher-url".

Is it required that the contributors have a website_url?

**Comment by tomwrobel** [comment]
Definitely not mandatory. I'm happy to drop the field if you advise it's unclear.

**Comment by AndrewBennet** [comment]
Dropping this field seems OK to me 👍
