### ISSUE TITLE
keywords: do FAST subject headings ever occur?

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#41]
As noted in the updated Symplectic -> ORA crosswalk xml file, if the Symplectic keyword is in the FAST scheme, then it should map to an ORA keyword.

Does symplectic use the FAST scheme anywhere: http://fast.oclc.org/

**Comment by AndrewBennet** [comment]
No, we don't by default include the FAST scheme in Elements. However, custom keyword schemes can be added to Elements...

**Comment by tomwrobel** [comment]
Cool, not to worry!
