### ISSUE TITLE
On-behalf-of header

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#44]
Just as a quick reminder of something that came up in today's call.

Sword 2 is able to save a given work as if it had been deposited by a given user, using the On-behalf-of header, where that value is a username (in Hyrax an email address).

It's perfectly fine for us if this is hard set to elements@symplectic.co.uk or something similar. However, I suspect that other clients may want this to be a configuration option.

**Comment by tomwrobel** [comment]
After discussion - this will work with the HTTP headers map. Can be set to a value in the crosswalk

**Comment by tomwrobel** [comment]
@AndrewBennet is this header being set in https://oxford-hyrax.elements.symplectic.org, and if so what value is it set to? When I create an object via Sword2 directly, it's creating as oraadmin@bodleian.ox.ac.uk, but current objects created via SE are creating as bhavana.ananda@bodleian.ox.ac.uk (which I think is because no value is being send)

**Comment by AndrewBennet** [comment]
There's a special field-map in the Deposit crosswalk called "http-headers". The "fields" which result from this map are used as HTTP header key-value pairs.

```
<!-- Specially named field map "http-headers". This is run and the results are provided to
Elements in order to add the key-value pairs as HTTP headers during the item deposit -->
<xwalk:field-map name="http-headers">
  <!-- To be uncommented when the On-Behalf-Of user is available -->
  <!--<xwalk:field-mapping to="On-Behalf-Of">
    <xwalk:field-source value="elements@symplectic.co.uk" />
  </xwalk:field-mapping> -->
  <xwalk:field-mapping to="Hyrax-Work-Type">
    <xwalk:field-source from="object.type" value-map="ora-work-type-mappings" />
  </xwalk:field-mapping>
</xwalk:field-map>
```

This is how we are producing the Hyrax-Work-Type header, and it _will_ be how the On-Behalf-Of header will be made. You can choose to set this to a hardcoded value, or read the email address from the logged in user or impersonated user. At the moment, it's not set at all, so I suppose the Sword endpoint will just be using the account with which the API-Key is associated?

**Comment by tomwrobel** [comment]
@AndrewBennet: I uncommented this and set this to oraadmin@bodleian.ox.ac.uk and it works. Brilliant, thank you
