### ISSUE TITLE
Languages are not appearing correctly in METS

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#47]
At the moment, languages are not appearing correctly in the METS

https://ora4-prd-symp.bodleian.ox.ac.uk/sword/collections/default/works/db78tc00b

contains:

```xml
                        <mods:languageTerm authority="iso639-2b" type="text">#&lt;ActiveTriples::Relation:0x0000561d0e9dbee0&gt;</mods:languageTerm>

```

**Comment by anusharanganathan** [comment]
have fixed this now. See https://github.com/CottageLabs/willow_sword/commit/7019059266c3fdfa9346452087e97c3ff94bc32d

**Comment by tomwrobel** [comment]
Thanks
