### ISSUE TITLE
Different kinds of personal identifiers (and record identifiers)

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#5]
Some identifiers attached to people in Symplectic would map to predefined fields in ORA, such as ORCID. Others would go into a catch-all contributors__contributor_identifier entry, and with the scheme going into contributors__contributor_identifier__contributor_identifier_scheme and the value into contributors__contributor_identifier__contributor_identifier

**Comment by tomwrobel** [comment]
For example:

```
<api:identifier scheme="SCOPUS">1234</api:identifier> -> 
<mods:nameIdentifier type="SCOPUS">1234</mods:nameIdentifier>

<api:identifier scheme="orcid">1234</api:identifier> -> 
<mods:nameIdentifier type="orcid_identifier">1234</mods:nameIdentifier>
```

**Comment by AndrewBennet** [comment]
Could you clarify how the catch-all representation would be represented in MODS? Would it be in the same form as the ORCID and Scopus identifier representation you posted (but with some other value in the `type` attribute?

If it _is_, then this can probably already be done with something like:

    <xwalk:field-source data-part="person:identifier">
      <xwalk:field-source subfield="nameIdentifier">
        <xwalk:field-source attribute-name="type" data-part="identifier:scheme" value-map="identifier-scheme-mapping"/>
        <xwalk:field-source data-part="identifier:value"/>
      </xwalk:field-source>
    </xwalk:field-source>

With a value-map which would perform mappings like:

- orcid --> orcid_identifier
- scopus --> SCOPUS
- etc

and pass everything through unchanged.

Will check that this works OK.

**Comment by tomwrobel** [comment]
So the sample MODS for both is this:
```
       <mods:nameIdentifier type="orcid_identifier">field:contributors__orcid_identifier</mods:nameIdentifier>
        <mods:nameIdentifier type="field:contributors__contributor_identifiers__contributor_identifier_scheme">field:contributors__contributor_identifiers__contributor_identifier</mods:nameIdentifier>
```
for example
```
       <mods:nameIdentifier type="orcid_identifier">0000-0003-3302-161X</mods:nameIdentifier>
       <mods:nameIdentifier type="universitycardnumber">A2268142</mods:nameIdentifier>
```

**Comment by AndrewBennet** [comment]
Great - this is designed for in the crosswalk engine. I'll leave this issue open for now so I remember to verify that it works!

**Comment by tomwrobel** [comment]
I'm extending this issue very slightly. In the data model we're creating a new catch all record identifiers field in exactly the same way the contributor identifiers field will work. I'm assuming that this will be the same in engine terms?

In MODS

```
 <mods:identifier type="pid">field:pid</mods:identifier>
 <mods:identifier type="field:record_identifiers__record_identifier_scheme">field:record_identifiers__record_identifier</mods:nameIdentifier>
```

example values:

```
 <mods:identifier type="pid">uuid:12345678-1234-1234-1234-12345678abcd</mods:identifier>
 <mods:identifier type="random_metadata_source_id">12345</mods:nameIdentifier>
```

**Comment by AndrewBennet** [comment]
This turned out to be a bit trickier than I expected, due to some quirks in the way the crosswalk engine was treating attributes, but I seem to have it working now, mapping input like:

```
<api:person>
  <api:last-name>Bennet</api:last-name>
  <api:initials>A</api:initials>
  <api:first-names>Andrew</api:first-names>
  <api:identifiers>
    <api:identifier scheme="arxiv-author-id">abc123</api:identifier>
    <api:identifier scheme="researcherid">ABC_Researcher_ID</api:identifier>
    <api:identifier scheme="orcid">1234-5678-9123-4567</api:identifier>
  </api:identifiers>
</api:person>
```

into MODS like:

```
<mods:name type="personal">
  <mods:displayForm>Andrew Bennet</mods:displayForm>
  <mods:namePart type="given">Andrew</mods:namePart>
  <mods:namePart type="family">Bennet</mods:namePart>
  <mods:alternativeName>
    <mods:namePart>A</mods:namePart>
  </mods:alternativeName>
  <mods:nameIdentifier type="arxiv-author-id">abc123</mods:nameIdentifier>
  <mods:nameIdentifier type="researcherid">ABC_Researcher_ID</mods:nameIdentifier>
  <mods:nameIdentifier type="orcid_identifier">1234-5678-9123-4567</mods:nameIdentifier>
</mods:name>
```

This can be achieved using a `value-map` which maps some specific scheme names (in this case, `orcid` --> `orcid_identifier`) and leaves other scheme names alone.

If this looks good to you I think we can close this one.

**Comment by tomwrobel** [comment]
yup, that looks right! closing
