### ISSUE TITLE
METS: journal info not round tripping properly

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#50]
See https://ora4-prd-symp.bodleian.ox.ac.uk/sword/collections/default/works/db78tc00b

article title and article number are not round tripping at present:

xml input

```xml
                    <mods:relatedItem type="host">
                        <mods:titleInfo>
                            <mods:title>Journal of Hyrax</mods:title>
                        </mods:titleInfo>
                        <mods:part>
                            <mods:detail type="article">
                                <mods:number>XXI</mods:number>
                            </mods:detail>
                            <mods:detail type="edition">
                                <mods:number>1st</mods:number>
                            </mods:detail>
                            <mods:detail type="issue">
                                <mods:number>7</mods:number>
                            </mods:detail>
                            <mods:extent unit="pages">
                                <mods:list>45-48</mods:list>
                            </mods:extent>
                            <mods:detail type="volume">
                                <mods:number>42</mods:number>
                            </mods:detail>
                        </mods:part>
                        <mods:physicalDescription>
                            <mods:form type="status">Published</mods:form>
                        </mods:physicalDescription>
                    </mods:relatedItem>
```

xml output

```xml
<mods:relatedItem type="host">
                        <mods:part>
                            <mods:detail type="edition">
                                <mods:number>1st</mods:number>
                            </mods:detail>
                            <mods:detail type="issue">
                                <mods:number>7</mods:number>
                            </mods:detail>
                            <mods:extent unit="pages">
                                <mods:list>45-48</mods:list>
                            </mods:extent>
                            <mods:detail type="volume">
                                <mods:number>42</mods:number>
                            </mods:detail>
                        </mods:part>
                        <mods:physicalDescription>
                            <mods:form type="status">Published</mods:form>
                        </mods:physicalDescription>
                    </mods:relatedItem>
```

**Comment by anusharanganathan** [comment]
Again the code for journal title exists - https://github.com/CottageLabs/willow_sword/blob/feature/ora_customizations/app/services/willow_sword/crosswalk_to_mods.rb#L648-L653

as does the code for article number

https://github.com/CottageLabs/willow_sword/blob/feature/ora_customizations/app/services/willow_sword/crosswalk_to_mods.rb#L658-L664

Need to test why it is not returning the value

**Comment by anusharanganathan** [comment]
The host and journal being assigned depends on the model extracted from type_of_work. In the mets submitted, set the type_of_work to article, dataset or universal test object.

I added universal test object to the model check. See commit https://github.com/CottageLabs/willow_sword/commit/ee60479610ea2492450e553007a9d40ad1c3a642

**Comment by tomwrobel** [comment]
Ah, that makes perfect sense. I hadn't anticipated that as a downside of the 'universal test object', but you're absolutely right.

We'll have to work on real objects soon.

One of the consequences of this is that we'll have to save more than one type of object. If Symplectic sends us a journal article, we'll have to detect that and process it accordingly. Ditto a patent, book, etc.

Out of interest, although I'm happy to code it, how would we go about detecting the type of work before saving? Could we do this via an HTTP header? Or would it be better to do this via a bit of XML parsing before processing?

**Comment by tomwrobel** [comment]
Sod it. I'll reopen this as a new ticket. This one is closed. thank you
