### ISSUE TITLE
Print citation for related item mapping where no DOI is present

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#52]
Spun off from #10 

In ORA, we keep two pieces of information about a 'related item' (in Symplectic a publication-publication relationship): the title of the related work (related_items__related_item_title), and a way to find that work.

There are two ways to find that work

1) via a URL: related_items__related_item_url OR (e.g. a DOI)
2) via a 'print citation': related_items__related_item_citation_text (e.g. 'Smith et al. (1999), Nature 15, 233-365')

Where
 
- a publication-publication relationship exists AND
- there is no DOI for the child 'related item'

We would like to receive a 'print citation' for the work.

Looking around Symplectic Elements, it seems that there are a few places where a citation can be generated for a given work. Is it possible to include this citation in the publication-publication relationship so that it can be crosswalked?

**Comment by tomwrobel** [comment]
After discussion with @AndrewBennet, we're moving this to post release discussion. We could build a citation generator in the crosswalk, but that's a lot of work. If necessary, we'll do this. Otherwise, we use the journal mapping in https://github.com/tomwrobel/ora_data_model/blob/9fda618eda8086f5fd0f5d51a0e5b1925a6c3f60/symplectic_to_ora_field_mapping-2.0.xml#L430

**Comment by jjpartridge** [comment]
@tomwrobel  this sounds sensible to me.  Thanks

**Comment by tomwrobel** [comment]
@jjpartridge thanks, closing
