### ISSUE TITLE
Type of work and sub-type-of-work mappings

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#53]
Related to #7 and #51 

A list of mapping instructions for ORA fields type_of_work and sub_type_of_work has been added to the [mappings file instructions](https://github.com/tomwrobel/ora_data_model/blob/master/symplectic_to_ora_field_mapping-2.0.xml)

Some of these are moderately complex and will require discussion. 

https://github.com/tomwrobel/ora_data_model/blob/9fda618eda8086f5fd0f5d51a0e5b1925a6c3f60/symplectic_to_ora_field_mapping-2.0.xml#L556-L743

@AndrewBennet do you understand the mappings, and can the engine do these mappings?

**Comment by jjpartridge** [comment]
@tomwrobel  This looks good to me - thanks

**Comment by tomwrobel** [comment]
@AndrewBennet can you do the double-check as discussed and then close?

**Comment by tomwrobel** [comment]
<table>
<tr><td>Hello</td><td>World</td></tr></table>

**Comment by tomwrobel** [comment]
Sub types are not being correctly mapped, we'll need to fix this in crosswalks (I don't know where the error lies!)

**Comment by tomwrobel** [comment]
@jjpartridge what is the status of these? Has it been subsumed into another ticket?

**Comment by mrdsaunders** [comment]
Subtypes are in the crosswalks - testing will tell whether they are working!

Deposit/Harvest SE type <-> ORA type/subtype
Deposit/Harvest SE journal article subtype field <-> ORA journal article subtypes

**Comment by tomwrobel** [comment]
@mrdsaunders can you close this ticket when you or @tobypitts and @jjpartridge are happy with the outcome?
