### ISSUE TITLE
Bad Request response when item doesn't exist

### ISSUE THREAD

**Issue by AndrewBennet** [tomwrobel/ora_data_model#55]
I'm seeing 400 Bad Request responses when requesting an item which has been deleted.
E.g.:

	Request Method: GET
	Request URL: http://ora4-prd-symp.bodleian.ox.ac.uk/sword/collections/default/works/sb397824g
	Response Status Code: 400
	Response Reason Phrase: Bad Request

Is this expected? At the moment, Elements is coded it to expect 404s for non-existent items, so this is giving me errors.

**Comment by tomwrobel** [comment]
A 400 response is what is specified by the Sword gem, see: https://github.com/CottageLabs/willow_sword/wiki/Usage#get-work-that-doesnt-exist

I've checked the Sword2 spec, and it doesn't list a specific error for object not found. On my limited understanding of HTTP/REST I agree that 404 might be better, but @anusharanganathan can no doubt advise.

**Comment by AndrewBennet** [comment]
OK - fair enough! I would slightly prefer a 404 over a 400, since a 400 could presumably also cover malformed request URLs (rather than this correctly-formed URL which refers to a non-existent item).

I have adjusted the code for now to interpret 400s are "item did not exist", but could change it if a change is made.

**Comment by tomwrobel** [comment]
I'll leave this one open for @anusharanganathan when she comes back from Japan, as there may well be best practice here I really don't understand. I agree (on my naive understanding of REST) that 404 does seem much better!

**Comment by AndrewBennet** [comment]
Just a quick note, as this seems the best place to record this:

I've made the Elements connector interpret both 400 and 404 as "the item doesn't exist". So, if there is a plan to change this behaviour, you can do so without breaking the integration.

**Comment by tomwrobel** [comment]
That's great, thanks!

**Comment by tomwrobel** [comment]
@anusharanganathan any update on your thoughts regarding this?

**Comment by tomwrobel** [comment]
Now returns a 404 for object not found
