### ISSUE TITLE
Things to build into crosswalks

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#56]
- [x] Role title and role order 
- [x] Multiple values in name identifiers: pick one
- [x] Don't take roles from generic.04 (this is job title)
- [x] Set deposit licence, how will this work
- [x] Impersonator: we need to crosswalk this - as a mods:person, the person who performed the impersonation, role = impersonator
- [x] Depositor should be either the depositor (if they were the logged in user), or the person who was being impersonated

**Comment by tomwrobel** [comment]
How does impersonator work?

**Comment by AndrewBennet** [comment]
The info about the "depositing user" is always the logged in user, not the Impersonated user.

**Comment by AndrewBennet** [comment]
I'm having a little difficulty in being able to determine which author is also the depositor (if any), and then outputting both roles for that person, as shown in the example https://github.com/tomwrobel/ora_data_model/blob/master/elements_xwalks/xwalk-out/9598-mets-2.0.xml#L136-L172

What I can easily do is output another `mods:name` element for the depositor. Would that be sufficient? Or should I keep looking for ways to merge the two?

**Comment by tomwrobel** [comment]
If we could look for ways to merge the two, that would be very useful. It isn't the end of the world, but it is a significant pain for reviewers!

I don't mean to be obtuse, but is it not possible to make an xpath-based query based on the elements user id? Both have this in all examples (they'd have to have a user id in order to be a depositor, I assume?)

**Comment by AndrewBennet** [comment]
Yeah, we can use XPath to make this work, we just then lose some of the nice capabilities of the xwalk framework of being able to lookup and reference different pieces of person-data in a robust (i.e. not breaking if the API format changes) way. I'll continue to look for a solution for this for now

**Comment by tomwrobel** [comment]
I assumed there were factors at play I didn't know! 

There are times, I think, where we (Oxford) will have to be prepared to fix the crosswalks if the API changes. We're already doing this, of course, in RT1. The gains of auto-linking depositor are such that we have to be prepared to maintain this part: it will save 30 seconds for EVERY item we review. That's significant to us :)

**Comment by AndrewBennet** [comment]
OK, I'm sold! Just trying out a solution now

**Comment by AndrewBennet** [comment]
I've got the impersonator/depositor stuff working it seems. It will require a redeploy of the Elements instance, which I will try to get done before the call tomorrow.

**Comment by tomwrobel** [comment]
Brilliant, thanks!

**Comment by AndrewBennet** [comment]
Did you say that you need the department info of the depositor? If the depositor/impersonator is linked to the publication, this is fine. If they are an unrelated user, I don't currently have that information available. I _do_ have their institutional_identifier and email_address, along with their name. Is that sufficient? Or do you think we need to expand the data made available to the crosswalk?

E.g., when depositing a publication authored by Daniel Hook and Carl Bender, while logged in as Daniel Hook and impersonating Kate Byrne, I get the following output:

```xml
<mods:name type="personal">
  <mods:displayForm>Carl M Bender</mods:displayForm>
  <mods:namePart type="given">Carl M</mods:namePart>
  <mods:namePart type="family">Bender</mods:namePart>
  <mods:alternativeName altType="initials">
    <mods:namePart>CM</mods:namePart>
  </mods:alternativeName>
  <mods:nameIdentifier type="email_address">c.bender@lilliput.edu</mods:nameIdentifier>
  <mods:nameIdentifier type="figshare-for-institutions-user-account-id">cbender</mods:nameIdentifier>
  <mods:nameIdentifier type="institutional_identifier">cbender</mods:nameIdentifier>
  <mods:affiliation>
    <ora:affiliation type="division">Department of Physics</ora:affiliation>
    <ora:affiliation type="department">School of Natural Sciences</ora:affiliation>
    <ora:affiliation type="oxford_college">TRUE</ora:affiliation>
  </mods:affiliation>
  <mods:role>
    <mods:extension>
      <ora:role_order>1</ora:role_order>
    </mods:extension>
    <mods:roleTerm type="text">Author</mods:roleTerm>
  </mods:role>
</mods:name>
<mods:name type="personal">
  <mods:displayForm>Daniel W Hook</mods:displayForm>
  <mods:namePart type="given">Daniel W</mods:namePart>
  <mods:namePart type="family">Hook</mods:namePart>
  <mods:alternativeName altType="initials">
    <mods:namePart>DW</mods:namePart>
  </mods:alternativeName>
  <mods:nameIdentifier type="email_address">d.hook@lilliput.edu</mods:nameIdentifier>
  <mods:nameIdentifier type="figshare-for-institutions-user-account-id">dwh</mods:nameIdentifier>
  <mods:nameIdentifier type="researcherid">C-4764-2008</mods:nameIdentifier>
  <mods:nameIdentifier type="orcid_identifier">0000-0001-9746-1193</mods:nameIdentifier>
  <mods:nameIdentifier type="arxiv-author-id">http://arxiv.org/a/hook_d_1</mods:nameIdentifier>
  <mods:nameIdentifier type="institutional_identifier">dwh</mods:nameIdentifier>
  <mods:affiliation>
    <ora:affiliation type="division">Theory Group</ora:affiliation>
    <ora:affiliation type="department">Digital Science</ora:affiliation>
    <ora:affiliation type="subdepartment">Theoretical physics</ora:affiliation>
    <ora:affiliation type="oxford_college">YES</ora:affiliation>
  </mods:affiliation>
  <mods:role>
    <mods:extension>
      <ora:role_order>2</ora:role_order>
    </mods:extension>
    <mods:roleTerm type="text">Author</mods:roleTerm>
  </mods:role>
  <mods:role>
    <mods:extension>
      <ora:role_order>1</ora:role_order>
    </mods:extension>
    <mods:roleTerm type="text">Impersonator</mods:roleTerm>
  </mods:role>
</mods:name>
<mods:name type="personal">
  <mods:displayForm>Ms Kate Byrne</mods:displayForm>
  <mods:namePart type="given">Kate</mods:namePart>
  <mods:namePart type="family">Byrne</mods:namePart>
  <mods:alternativeName altType="initials">
    <mods:namePart>K</mods:namePart>
  </mods:alternativeName>
  <mods:nameIdentifier type="email_address">kbyrne@lilliput.edu</mods:nameIdentifier>
  <mods:nameIdentifier type="institutional_identifier">kbyrne</mods:nameIdentifier>
  <mods:extension>
    <ora:role_order>1</ora:role_order>
  </mods:extension>
  <mods:roleTerm type="text">Depositor</mods:roleTerm>
</mods:name>
```

**Comment by AndrewBennet** [comment]
(Ignore "oxford_college = YES", my database is different to Oxford's!)

**Comment by tomwrobel** [comment]
@AndrewBennet deposit licence ticket off as we know how this will be dealt with - I've re-opened #8 to track the issue - should be a small change
