### ISSUE TITLE
oxford-hyrax.elements.symplectic.org is down

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#57]
Hi Andrew

The test server appears to be down. 

I'm trying to organise people to do testing in order to get the approval at our end done as soon as possible. Sorry to be a pain, but if people actually try to test and can't I'll be getting emails soon.

Is this a known issue?

**Comment by AndrewBennet** [comment]
This is probably a complication of the server downtime that happened last night. It's being worked on right now. I don't have the details of what's happened; I'll let the infrastructure people focus on fixing it

**Comment by AndrewBennet** [comment]
Ok, we're back online. Sorry about the outage 😳

**Comment by tomwrobel** [comment]
Thanks!
