### ISSUE TITLE
Publication status and public file URL display in SE

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#61]
publication status and has public url are not as expected in Repotool 2/SE:

See: https://oxford-hyrax.elements.symplectic.org:8446/viewobject.html?cid=1&id=983398

the file link should be the link specified in file_public_url

The publication status of the object (is that the 'Live' setting) is incorrect for objects with files under embargo, e.g.

https://oxford-hyrax.elements.symplectic.org:8446/viewobject.html?cid=1&id=983403

The file should be under embargo and is displaying as 'Live'. is this correct?

**Comment by tomwrobel** [comment]
Create task for turning in_progress into record_requires_review

**Comment by tomwrobel** [comment]
new issue, time requests to OAI-PMH are in GMT

**Comment by AndrewBennet** [comment]
Fixed issue 1 - file URL is now being xwalked from `symp:hasPublicUrl`.

**Comment by AndrewBennet** [comment]
As for issue 2 - if I've understood correctly, this is expected behaviour. We specify that the files are embargoed, but the item can still be Live. This should be interpreted as "the item metadata is accessible online, but the file itself is restricted"

**Comment by tomwrobel** [comment]
We can, however in order to help this, see #65 on whether or not the record is public in ORA: Publication status (ORA record) - record_publication_date or has_public_url. It is one of these values, not any Hyrax visibility status, that should be used to determine visibility. We make sure the item is set to 'visible' in Hyrax so that it shows up in the OAI-PMH :)

**Comment by tomwrobel** [comment]
Would it be possible to judge Symplectic repository item status with the following logic:

IF has_public_url is set OR record_publication_date is set, then 'Public'
Otherwise use record_review_status

**Comment by AndrewBennet** [comment]
This logic is in place on the test server inbound xwalks not, though I haven't tested it against a real record with this data.

**Comment by tomwrobel** [comment]
Tested and working :) closing
