### ISSUE TITLE
Permit subsequent file deposit

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#62]
Once a record has had a file deposited, it should be possible for a user to make a subsequent deposit to that record

**Comment by AndrewBennet** [comment]
I'm having a look into this now, to see what the extent of the extra development would be to include this.

Just so we're clear - the "subsequent deposit operation" should consist of Elements uploading additional binary files and file metadata, in one-by-one Sword API calls... followed by a call to say that the item is "ready"? Or would the usual In-Progress handling cover that?

**Comment by tomwrobel** [comment]
That’s absolutely right. An additional binary file and metadata for that file for each newly deposited file, with in_progress set to false on the last action

**Comment by AndrewBennet** [comment]
OK great. If that's the case, then I think I will be able to get this in to the 5.15 release too. We'd need to redeploy the Elements instance at some point to enable that functionality (which would be a good idea to do anyway, as there has been a lot of other changes go in); let's chat on Monday.

**Comment by tomwrobel** [comment]
This is now done and confirmed as working. Closing
