### ISSUE TITLE
Deposit file on claimed record

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#64]
Related, possibly, to #62

I went to https://oxford-hyrax.elements.symplectic.org:8446/viewobject.html?cid=1&id=489636 (impersonating the user Fiona Macintosh) and claimed it. I then tried to deposit a file and got an error from Repotool 2 (ORA is experiencing problems)

**Comment by AndrewBennet** [comment]
I'll investigate. I've noticed that the System Log is filling up with errors attempting to download items for the RT1 connection, which is still configured, but inaccessible. Is there any part of your testing which will require this RT1 connection to be maintained? I would like to remove it to reduce the errors polluting the system log (and possibly slowing the system down at times).

**Comment by AndrewBennet** [comment]
Hm, yes - I'm seeing errors relating the RT1 connection for that specific publication, but nothing about the new RT2 connection. It's possible that the RT1 connection timeouts caused this RT2 issue too somehow...

![image](https://user-images.githubusercontent.com/2078225/56053096-0e93ac00-5d4b-11e9-9c64-ab28246304bd.png)

**Comment by tomwrobel** [comment]
You can go ahead and disable RT1 for now, yes! Please don’t purge it entirely, as we might use it to test deployment of the new system. 

If you have to purge it, then it’s not a massive deal

**Comment by AndrewBennet** [comment]
Yeah, I'd have to purge it unfortunately. The RT1 and RT2 connections share the general "can deposit to repository" permission, so I can't just hide the RT1 one.

If this is still OK to purge, let me know 👍

**Comment by tomwrobel** [comment]
Purge away

**Comment by AndrewBennet** [comment]
I'll close this under the assumption that it was related to the errors being caused by the RT1 connection. If it re-occurs, let me know

**Comment by tomwrobel** [comment]
@AndrewBennet this issue has re-occurred in ORA4 deployment testing. Could you take a look? I'm happy to walk you through!

We have:

1) claimed a record in Oxris (with no deposited files)
2) attempt to deposit files
3) file deposit fails with the message "This deposit was unable to be completed. Please contact your repository administrator for assistance."

**Comment by AndrewBennet** [comment]
Uh oh! OK, could you first take a look in the system log for any errors from around that time, and copy the technical details part here? Or is there don't seem to be related errors, we can skype and run through it together

**Comment by tomwrobel** [comment]
I'm free from 3pm today?

**Comment by AndrewBennet** [comment]
Can we do 3:45?

**Comment by tomwrobel** [comment]
Yup! 15:45 it is

**Comment by tomwrobel** [comment]
Possible error in Hyrax

```
I, [2019-06-26T15:50:06.584171 #27180]  INFO -- : [201344ea-f2c0-4639-8125-1370f6df9938] Completed 500 Internal Server Error in 296ms (ActiveRecord: 8.7ms)
F, [2019-06-26T15:50:06.585424 #27180] FATAL -- : [201344ea-f2c0-4639-8125-1370f6df9938]   
F, [2019-06-26T15:50:06.585476 #27180] FATAL -- : [201344ea-f2c0-4639-8125-1370f6df9938] NoMethodError (undefined method `each' for nil:NilClass):
F, [2019-06-26T15:50:06.585501 #27180] FATAL -- : [201344ea-f2c0-4639-8125-1370f6df9938]   
F, [2019-06-26T15:50:06.585590 #27180] FATAL -- : [201344ea-f2c0-4639-8125-1370f6df9938] vendor/cache/ruby/2.5.0/bundler/gems/willow_sword-942d19aee0d8/app/services/willow_sword/assign_mets_to_model.rb:852:
in `assign_contributor_hash'
[201344ea-f2c0-4639-8125-1370f6df9938] vendor/cache/ruby/2.5.0/bundler/gems/willow_sword-942d19aee0d8/app/services/willow_sword/assign_mets_to_model.rb:358:in `assign_name_person'
[201344ea-f2c0-4639-8125-1370f6df9938] vendor/cache/ruby/2.5.0/bundler/gems/willow_sword-942d19aee0d8/app/services/willow_sword/assign_mets_to_model.rb:259:in `block in assign_name'
[201344ea-f2c0-4639-8125-1370f6df9938] vendor/cache/ruby/2.5.0/bundler/gems/willow_sword-942d19aee0d8/app/services/willow_sword/assign_mets_to_model.rb:245:in `each'
[201344ea-f2c0-4639-8125-1370f6df9938] vendor/cache/ruby/2.5.0/bundler/gems/willow_sword-942d19aee0d8/app/services/willow_sword/assign_mets_to_model.rb:245:in `assign_name'
[201344ea-f2c0-4639-8125-1370f6df9938] vendor/cache/ruby/2.5.0/bundler/gems/willow_sword-942d19aee0d8/app/services/willow_sword/assign_mets_to_model.rb:16:in `assign_mets_to_model'

```

**Comment by tomwrobel** [comment]
@jjpartridge 

After call w. @AndrewBennet identified as likely to be a crosswalk ingest error in ORA. Fixes to come tomorrow

**Comment by tomwrobel** [comment]
@AndrewBennet I think I solved it: a crosswalk error in the outbound Symplectic crosswalk. Depositor wasn't being wrapped in a mods:role element, so the crosswalk was failing.

I've fixed the error in the crosswalk and updated the file in the repo.
