### ISSUE TITLE
Metadata read by OA Monitor from Hyrax

### ISSUE THREAD

**Issue by eugeniobarrio** [tomwrobel/ora_data_model#65]
@AndrewBennet how does the OAM calculate or read the 
- Publication status: 
- Compliant file status:
- Repository item status:

from https://github.com/tomwrobel/ora_data_model/issues/2 the latter is no longer calculated from public URL, file, licence, but read directly from a field crosswalked from ORA

**Comment by tomwrobel** [comment]
Dear @eugeniobarrio 

Before we discuss this further, can you confirm that the following 'What this means' column is correct? @jjpartridge is away

The relevant fields in ORA are (as I understand them):

| Field | What this means | ORA field which holds this metadata |
| Publication status (version of record) | Publication status of the research object, e.g. has a journal article been published by the journal? has a monograph been published by the publisher? | citation_publication_status |
| Publication status status (ORA record) | Is the record published on the ORA public front end? | record_publication_date (if set, record is published) AND/OR has_public_url (the URL of the public ORA record) |
| Compliant file status | Rioxx version of a file | binary_files__file_rioxx_file_version |
| Compliant record status | Was the object compliant on deposit in ORA? | ref_compliant_at_deposit |
| Repository item status | Status of the record within the ORA system: deposited, reviewed, or published | record_review_status |

**Comment by tomwrobel** [comment]
This issue is also related to #61 - and I suspect the two may be the same issue

**Comment by tomwrobel** [comment]
Publication status in OA monitor: How is this calculated? and does OA monitor take information from RT2 for it?

Compliant file status in OA monitor: how is this calculated? and does OA monitor take information from RT for it?

**Comment by tomwrobel** [comment]
Publication status is item level, highest level precedence record: as far as ORA is concerned, this field is citation_publication_status, and ORA will provide a crosswalk mapping between SE OA Monitor values and ORA values in the same way as review statuses in #2.

**Comment by tomwrobel** [comment]
Compliant file status: sort of the same as compliant status: if one file is compliant, then the record is compliant. @AndrewBennet to update

**Comment by tomwrobel** [comment]
Repository item status in OA Monitor: 'Live' is the item level status, and needs new value mappings. Will be set correctly once #2 is resolved. @AndrewBennet will double check on RT1 'Live' vs RT2 'Public' terminology in the buttons

**Comment by AndrewBennet** [comment]
The mappings between the RT2 status names and the OA Monitor names are shown below:

| RT2 Name | OA Monitor Name |
| -----------|------------------------|
| Unknown | Unknown |
| Private (in preparation) | Deposit incomplete |
| Private (in review) | In review |
| Public | Live |
| Private (withdrawn) | Withdrawn |
| Private | Deposited (not live) |
| Deleted | Deleted |

It seems like the OA Monitor is using the RT1 name equivalents, probably due to the fact that the OA Monitor can display both RT1 and RT2 items.

**Comment by tomwrobel** [comment]
@AndrewBennet thanks. I believe we can now close. If testing throws anything up, we can reopen.
