### ISSUE TITLE
Frequency of harvest and updates

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#67]
In previous versions of Sympectic Elements, it was possible to configure the frequency of harvest and frequency of updates for a given data source.

We can't find that option for the Hyrax connector in RT2. Where should we be looking?

Related to signoff criteria 2.4b

**Comment by AndrewBennet** [comment]
For all of our RT2 sources, the time period between automatically enqueued harvests is not configurable (1 hour for differential, 30 days for full). However, full harvests can be manually enqueued using a button in the UI. The ability to adjust the frequency of the differential harvests for our RT2 integrations is not something that has been requested before.

**Comment by tomwrobel** [comment]
Accepted and closing!
