### ISSUE TITLE
Type of work

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#7]
We will need to generate a list of SE work types so that they can be mapped against ORA types of work (including sub types).

In the first instance, we'll need a list of all types of work in SE

**Comment by AndrewBennet** [comment]
The default list of object type names in Elements is as follows:

 - artefact
 - book
 - chapter
 - composition
 - conference
 - dataset
 - design
 - exhibition
 - figure
 - fileset
 - internet-publication
 - journal-article
 - media
 - other
 - patent
 - performance
 - poster
 - presentation
 - report
 - scholarly-edition
 - software
 - thesis-dissertation

There may be customer publication types in use which also need mapping, though.

**Comment by tomwrobel** [comment]
@jjpartridge can you provide a list of ORA item types and sub types?

**Comment by AndrewBennet** [comment]
I just checked on your Elements system, you also have the custom types "Edited Books" and "Working papers"

**Comment by jjpartridge** [comment]
@tomwrobel we have the base types, but there is still a bit of work that need sto be done on what sub-types we are wanting in ORA4. 

Types as they currently stand, but are likely for revision:

Thesis
Dataset
- Fileset
- Media
- Software
Article
- Editorial
- Review
- Correspondence
- Comment
- Abstract
Conference item
- Exhibition
- Presentation
Book
- Scholarly edition
- Edited book
Book section
- Chapter
Working paper
Poster
Patent
Report
Physical Object
- Artifact
Composition
- Performance
Internet publication
Ephemera
- Newsletter
- Pamphlet

**Comment by jjpartridge** [comment]
@thomas-wrobel I think this is what we want.

In SE there is the item type "Other" currently the ORA4 data model does not have a corresponding item type - perhaps this needs to be added...

[Item_types_and_subtypes.xlsx](https://github.com/tomwrobel/ora_data_model/files/2971706/Item_types_and_subtypes.xlsx)

**Comment by tomwrobel** [comment]
@jjpartridge a list of mappings has been added to the symplectic_to_ora_field_mapping XML file. Please take a look!
