### ISSUE TITLE
Publication Status crosswalking

### ISSUE THREAD

**Issue by AndrewBennet** [tomwrobel/ora_data_model#70]
In order to correctly crosswalk the publication-status field ([field:host_publication_status](https://github.com/tomwrobel/ora_data_model/blob/master/ora_datamodel_to_mets-2.0.xml#L437)) from Hyrax to Elements, we need to determine the mapping of values between the two systems.

In example records, this has the value "TBC". The values we would want to map to are those available in Elements (see attached screenshot):

![image](https://user-images.githubusercontent.com/2078225/56206606-af80b080-6044-11e9-8501-667fc955b097.png)

**Comment by tomwrobel** [comment]
@AndrewBennet I've amended that particular value to read 'In preparation'. I'll discuss here about what values we use for this field, and how they should be crosswalked.

**Comment by tomwrobel** [comment]
| ORA host_publication_status | Symplectic publication-status |  Notes |
|:---------------------------------------:|:---------------------------------------:|:---------------------------------------------|
| notpublished | Unpublished ||
| submitted | Submitted ||
| accepted | Accepted ||
| impress | In preparation ||
| published | Published ||
| <no mapping> | Published online | Published and Published online both 'published' in ORA, there is no way to disambiguate the two |

**Comment by AndrewBennet** [comment]
:+1: Cheers - that's perfect. I've updated the crosswalk for the inbound mapping on the test server. Should this be set for the outbound mapping too?

**Comment by tomwrobel** [comment]
Yup, I think so. We'd appreciate it!

**Comment by AndrewBennet** [comment]
Done

**Comment by AndrewBennet** [comment]
Actually, this doesn't seem to be mapping quite right. I'll investigate and update when I know why

**Comment by tomwrobel** [comment]
Let me know if you want me to tweak test values.

I've given t148fh12j 'notpublished' and 'rn3011364' 'inpress'

**Comment by AndrewBennet** [comment]
Thanks - I think its working now :)

**Comment by tomwrobel** [comment]
Where would I look for testing?

**Comment by AndrewBennet** [comment]
You can look in the Hyrax record metadata, on the viewobject page. The publication-status field has a display name of "Status”. Or you could look in the OA Monitor using the filter.

**Comment by tomwrobel** [comment]
Done, tested, and closing!
