### ISSUE TITLE
Public url of record is wrong in Symplectic Elements

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#71]
If a record in Hyrax is set to published, then the URL for the public record should be taken from the ORA field 'has_public_url' and not a link to the Hyrax record.

Currently, for https://oxford-hyrax.elements.symplectic.org:8446/viewobject.html?cid=1&id=983570

link shown: https://ora4-prd-symp.bodleian.ox.ac.uk/concern/universal_test_objects/41687h45k
correct value (has_public_url): https://ora.ox.ac.uk/testgolf

**Comment by AndrewBennet** [comment]
Fixed! I've queued a full harvest, so all the existing records should update soon.

**Comment by AndrewBennet** [comment]
Yep, seems OK now:

![image](https://user-images.githubusercontent.com/2078225/56358662-36659280-61d7-11e9-8db3-a98de628c761.png)

**Comment by tomwrobel** [comment]
Thank you! Fixed and closing
