### ISSUE TITLE
file_embargo_end_date displays wrongly in SE on the day file is released

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#72]
This seems like a very small error, but I suspect it may cause us some pain. If necessary it can be moved to post migration development.

The issue is as follows. IF a file for a record with record_review_status 'Public':

- has file_embargo_end_date 2019-04-19 (today)
- has file_made_available_date 2019-04-19 (today)
- file_public_url of a value (e.g. 'http://testurl.com)

Then no link to the file appears and it still displays as under embargo.

This is clearly because embargo_end_date has not passed. However, if I think that we model embargo end dates as the day on which a file can be released, whereas Symplectic considers them to be the last day the embargo is in effect. I don't know which is right!

- [x] @AndrewBennet can you confirm that this is expected behaviour?
- [x] @eugeniobarrio @jjpartridge is this how we consider embargo end dates in ORA?
- [x] @eugeniobarrio @jjpartridge is this behaviour acceptable?

**Comment by AndrewBennet** [comment]
I would've thought that we treat an item as publicly available _on_ the date that it was marked as being embargoed until.

I notice you say 2019-04-19 is today... but that's tomorrow. Is this the source of the problem?

**Comment by tomwrobel** [comment]
Crap. That would be a really stupid mistake. I’ll check!

**Comment by tomwrobel** [comment]
@AndrewBennet apologies, you're quite right. Using today's actual date (18 April) the behaviour is absolutely as expected. Many apologies!
