### ISSUE TITLE
Embargo information is only visible in SE if an item is live

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#73]
If a record in SE does not have the status of 'live' in ORA (public), then the embargo information for that file (while present) does not display in the SE publicaton page, or in the OA monitor display (you may be able to filter for it though, I haven't tested).

See https://oxford-hyrax.elements.symplectic.org:8446/viewobject.html?cid=1&id=983573

@eugeniobarrio @jjpartridge is this expected behaviour?

**Comment by AndrewBennet** [comment]
I'm pretty sure this behaviour is the same as RT1, btw

**Comment by tomwrobel** [comment]
I don't doubt it, but I do need to check because it's not something I'm too familiar with :)

--
Tom Wrobel
Software Engineer - BDLSS
thomas.wrobel@bodleian.ox.ac.uk / 01865 277608

________________________________________

**Comment by tomwrobel** [comment]
Discussed w. @eugeniobarrio on the phone 11:41 23/4/2019, this behaviour is expected, closing.
