### ISSUE TITLE
Depositor licence

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#8]
ORA would like to store the depositor licence (ORA field: record_deposit_licence) as a URI which identifies a specific version of the deposit licence. If the deposit licence has not been selected, the value would not be set.

We need to agree on a URI for the deposit licence, and find a way to crosswalk this value into record_deposit_licence

**Comment by AndrewBennet** [comment]
For RT2, deposit licences are not uploaded to the repository, but instead a configured identifier of the selected deposit licence is exposed to the crosswalks. This sounds like it aligns perfectly with what you want to achieve.

For example - DSpace configuration page to set up licences:
![DSpace licence config](https://user-images.githubusercontent.com/2078225/52348487-58df7080-2a1c-11e9-924e-c1692e6f3aca.png)

And then when depositing, the identifier of the selected licence in the dropdown is available in the crosswalks (if there is only 1 licence, there is no dropdown, and the message states that you agree to it by depositing).
![DSpace deposit page](https://user-images.githubusercontent.com/2078225/52348437-377e8480-2a1c-11e9-9715-9d79d7db01ac.png)

**Comment by tomwrobel** [comment]
That sounds absolutely perfect. Closing

**Comment by tomwrobel** [comment]
Reopening, because we now have a crosswalkable value, as defined in the update to the crosswalk mapping file. @AndrewBennet bumping you for visibility :)

**Comment by AndrewBennet** [comment]
Great - I've added the mapping. Although, since we are sending an identifier URL to this field, when we read it back do you want us to map it to some display name?

**Comment by tomwrobel** [comment]
For display in Symplectic Elements? yes, probably: there's a field for licence name in the deposit licences section, isn't there?

**Comment by AndrewBennet** [comment]
Yes, there will be a display name stored in Elements; we'll need to replicate the mappings of the URLs to Display Names to the inbound crosswalk, but that's fine.

Actually, I think there's a bit of confusion (on my part) about the remit of the Elements fields author-licence and publisher-licence. I think they are both used to store CC-type licence values, and so perhaps some other field would be more appropriate for the deposit licence.

I'll chat soon with some of the team who better understand this area of our metadata model, and get back to you.

**Comment by tomwrobel** [comment]
@AndrewBennet bumping :)

**Comment by AndrewBennet** [comment]
OK, having discussed this internally, I think we should be using `author-licence` to store the CC-style licences, and if you need to capture the selected deposit-licence, a custom Elements field can be created. I'll adjust the crosswalks accordingly now to just use `author-licence`.

**Comment by tomwrobel** [comment]
Brilliant, thank you! Closing
