### ISSUE TITLE
Oxris Configuration Instructions/Script

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#80]
This ticket tracks the creation of a script that will be followed in order to configure SE (oxris) successfully before, during, and after ORA4 Go Live.

It should cover:

1) How to create and configure the Hyrax connection
2) How to update the Repotool2 metadata only connection
3) How to enable the Hyrax Repotool2 deposit process
4) How to disable the Repotool1 metadata connection without harm

**Comment by jjpartridge** [comment]
https://unioxfordnexus-my.sharepoint.com/:w:/g/personal/bodl1072_ox_ac_uk/EbeCUbi2pGNPu1EvmoCcI5sB-kl0kEaasxeaS9z4cF97Qg?e=a0DVbu

**Comment by tomwrobel** [comment]
Yup, that's the draft, thank you! I'd forgotten about that...
