### ISSUE TITLE
Affiliation mappings in ORA/Hyrax using biztalk values

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#81]
Related Trello ticket: https://trello.com/c/emfo6L6M/748-part-of-53113pts-map-affiliations-using-biztalk-values

RULES FOR CROSSWALKS AND STORAGE

The tables within the affiliation database have been closely aligned with the values expected from Symplectic Elements and the BizTalk feed. However due to the way that information is presented from that feed the values are not necessarily what we would want to have stored or displayed. As such additional things need to be considered on crosswalk mapping and processing new deposits.

For crosswalks purposes the column “seAltName” needs to be checked within each table.

 

Mappings:

-          Generic01 = contributors__division

-          Primary Group = contributors__department

-          Generic07 = contributors__department & contributors__sub_unit

-          Generic03 = contributors__oxford_college

 

Each of these values will need to be mapped and checked against the tables in the affiliations database. The mapping will need to take place on both the ‘Name’ fields and the “seAltName” field, example below of a common affiliation for SE

MEDICAL SCIENCES |   | Nuffield Dept of Population Health |   | H6 CLINICAL TRIAL SERVICE UNIT
-- | -- | -- | -- | --

Rules for mapping

-          If the values (after look-up mapping) are the same in each property of the affiliation, e.g. Division = GLAM; Department = GLAM; sub-division = GLAM, then only process this to review at the highest level of the affiliation e.g. Division = GLAM.

 

The value that we would like to store in Hyrax should be the human friendly version and therefore the ‘Name’ values within the Affiliations database (e.g. divisionName; departmentName, etc)

**Comment by tomwrobel** [comment]
@jjpartridge we need to talk about this tomorrow/soon

**Comment by jjpartridge** [comment]
@tomwrobel i'm around tomorrow.

**Comment by tomwrobel** [comment]
@jjpartridge this is now fixed in code, but not deployed. Can you test this afternoon after the QA redeploy?

**Comment by tomwrobel** [comment]
@jjpartridge deployed and, I think, tested (via sword2 at least, I don't know what values Symp is sending)
