### ISSUE TITLE
Record content source should be set as "Symplectic Elements"

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#83]
As per Symplectic to ORA field mapping, line 435, the record_content_source should be "Symplectic Elements"

**Comment by mrdsaunders** [comment]
@tomwrobel  - is any action needed or happened or is this a FYI?

**Comment by tomwrobel** [comment]
@mrdsaunders 

Action is needed. There is a fixed value that should be being sent for the ORA field record_content_source of "Symplectic Elements" that I don't think is being set

**Comment by mrdsaunders** [comment]
Got it, thanks Tom. Will start on deposit xwalks later this week so will address it then. I'l leave this issue open until then.

**Comment by mrdsaunders** [comment]
<xwalk:field-mapping to="recordInfo">
        <xwalk:field-source subfield="recordContentSource" value = "Symplectic Elements">
        </xwalk:field-source>
      </xwalk:field-mapping>
