### ISSUE TITLE
SE finish-date mapping

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#86]
SE `finish-date` is mapped to ORA `event_finish_date`. 

`<symplectic_field name="finish-date"><ora_field>field:event_finish_date</ora_field></symplectic_field>`

However this doesn't appear in ORA to mets or sample mets. Should the mapping to ORA actually read `event_end_date` as per the following mets?

`ORA to mets`:
```
<mods:originInfo>
    <mods:dateOther point="start" type="event_date">field:event_start_date</mods:dateOther>
    <mods:dateOther point="end" type="event_date">field:event_end_date</mods:dateOther>
</mods:originInfo>
```

**Comment by jjpartridge** [comment]
@mrdsaunders @tomwrobel  Yes. The correct ORA Data Model field is 'event_end_date'. Thanks

**Comment by mrdsaunders** [comment]
Pull (merge) request #96
