### ISSUE TITLE
SE field 'location'

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#88]
From `SE to ORA field mapping`:
```
<symplectic_field name="location">
    <if test="record is a Conference, Exhibition, Performance, Presentation, etc."><ora_field>event_location</ora_field></if>
    <if test="record is a Physical item"><ora_field>physical_location</ora_field></if>
    <if test="record is a Journal Article"><ora_field>citation_place_of_publication</ora_field></if>
    <if test="record is a Patent">patent_territory</if>
</symplectic_field>
```

Q1: Do we need to add dataset to the mapping?

`<if test="record is a dataset"><ora_field>digital_storage_location</ora_field></if>`

Q2: Is there any other event type output in `etc` in `Conference, Exhibition, Performance, Presentation, etc.`?

Q3: For journal articles, `citation_place_of_publication` goes to 2 SE fields - it also goes to:
`<symplectic_field name="place-of-publication">ora_field>citation_place_of_publication</ora_field></symplectic_field>`

For harvest crosswalk, we can decide which or both to crosswalk. For the deposit crosswalk, which SE field should crosswalk to `citation_place_of_publication`? (or do you want to apply logic)?

**Comment by tomwrobel** [comment]
@mrdsaunders @jjpartridge 

Q1: If the field is being used for storage location, then yes. However, it would be a conditional mapping: data_digital_storage_location where the dataset was digital and present on an external system, data_physical_storage_location where the dataset is being stored on physical media. Jason can confirm.

Q2: I don't think so. Etc. was being used quite lazily here

Q3. The ORA field should map back to place-of-publication, and the SE value in place-of-publication should win out against location if the two are present but differ.

**Comment by jjpartridge** [comment]
@mrdsaunders @tomwrobel 
I think that the easiest distinction would be:
Q1: If the deposit has a DOI then location to be set as data_digital_storage_location. If no DOI is set then set data_physical_storage_location
Unless you can recognise whether a URL has been entered?

**Comment by mrdsaunders** [comment]
Could recognise a URL (using RegEx?) but it won't be in the first pass of Crosswalks as I'd need to learn how to do it.

**Comment by mrdsaunders** [comment]
Proposed Q3:
```
<symplectic_field name="location">
    <if test="record is a Conference, Exhibition, Performance, Presentation, etc."><ora_field>event_location</ora_field></if>
    <if test="record is a Physical item"><ora_field>physical_location</ora_field></if>
    <if test="record is a Journal Article AND place-of-publication has a value = False"><ora_field>citation_place_of_publication</ora_field></if>
    <if test="record is a Patent">patent_territory</if>
</symplectic_field>
```

```
<symplectic_field name="place-of-publication"><ora_field>citation_place_of_publication</ora_field></symplectic_field>
```

**Comment by mrdsaunders** [comment]
Agreed as above ORA-SE 17/10/2019

**Comment by mrdsaunders** [comment]
Open as @mrdsaunders still needs to update deposit crosswalk as per Q3:
```
map to citation _place_of_publication
    if place-of-publication has a value:
            use place-of-publication
    else:
        if location has a value:
            use location
```

**Comment by tomwrobel** [comment]
@mrdsaunders understood, changing assigner

**Comment by tomwrobel** [comment]
@mrdsaunders is this ticket still open?

**Comment by mrdsaunders** [comment]
Yes!

**Comment by mrdsaunders** [comment]
For the record:

- Place of publication is not used by any external data sources
- Location is labelled out of the box with 'country' for journal articles in SE, and populated with country value for PubMed record but has no data from other sources

Can I ask in the ORA4 data model is citation_place_of_publication expecting country values or any geographic location?

**Comment by tomwrobel** [comment]
The value is not a controlled list. It's free text, so any country or more precise location value is acceptable: 'Berlin'; 'Berlin, Germany'; or 'Germany' would all be acceptable values.

citation_place_of_publication means: if we have to reconstruct a print citation for this work, and that print citation format has place of publication as a concept (for monographs, etc. this is very common), what string goes in that value?

**Comment by mrdsaunders** [comment]
Due to limitations in the crosswalk and pending discussions with Andrew Bennett, I am unable to write the deposit crosswalk for:
```
map to citation _place_of_publication
    if place-of-publication has a value:
            use place-of-publication
    else:
        if location has a value:
            use location
```
Firstly is it acceptable to just write from one field, and if so, should I map from:

- location (has country value from PubMed records and also data from manual records), or
- place-of-publiction (only has data from manual records)

The former will get more data.

**Comment by mrdsaunders** [comment]
Pending answer I have set it to read from SE location.
