### ISSUE TITLE
ORA binary_files__file_embargo_end_date to SE 

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#89]
ORA `binary_files__file_embargo_end_date` is mapped to  SE `embargo-release-date`. 

I believe ORA `binary_files__file_embargo_end_date` is at file level whereas SE  `embargo-release-date` is at object level.

Hence there may be multiple dates to write to a single SE field. the first is written with the error:
`<!--[WARNING] Record uuid:12345678-1234-1234-1234-12345678abcd [from Xsl]: embargo-release-date field: more than 1 date field found (99991231)-->. `

Can I check that the mapping and my assumptions about file vs object level are correct?

**Comment by tomwrobel** [comment]
@mrdsaunders that's correct, it's entirely possible to have more than one file_embargo_end_date on an ORA object, depending on the nature of the object.

You could simplify this for most objects by only looking at the file with a RIOXX file version. But even that's not guaranteed to work. 

Given the importance of this field to REF, can I suggest we discuss tomorrow if the following assumption is safe:

If more than one date field is present, then always take the latter of the two dates (if this is even possible!)

**Comment by mrdsaunders** [comment]
I don't think that <xwalk:condition> support < or > to take the latter of two dates. Will revisit this once I have worked though the non-problematic ones!

**Comment by mrdsaunders** [comment]
Following our call with S Ltd on 24/10/2019, they have confirmed that embargo-release-date is in fact at file level so not a problem.
