### ISSUE TITLE
Mapping from SE field 'medium'

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#92]
The SE to ORA mapping document reads:
`<symplectic_field name="medium"><no_mapping/></symplectic_field>`
However should this in fact read:
'`<symplectic_field name="medium">physical_form</symplectic_field>`?

And map to the mets:
```
<mods:physicalDescription>
        <mods:form type="collection_name">field:collection_name</mods:form>
        <mods:form type="physical_form">field:physical_form</mods:form>
        <mods:form type="physical_dimensions">field:physical_dimensions</mods:form>
</mods:physicalDescription>
```

**Comment by tomwrobel** [comment]
@jjpartridge I don't *think* so, unless its for Physical items, where I can see we would map it to physical_form. Otherwise, no

**Comment by mrdsaunders** [comment]
OK. I will amend mapping to:
```
<symplectic_field name="medium">
        <if test="record is a Physical item"><ora_field>physical_form</ora_field></if>
        <else><no_mapping/>
 </symplectic_field>
```
Let me know if you _would_ like the value of the SE `medium` field mapped to ORA field `physical_form` for any other type.

**Comment by tomwrobel** [comment]
That's right! Although if that's the amendment, please make sure you put in a closing `</else>` tag :)

**Comment by mrdsaunders** [comment]
Cheers.

**Comment by jjpartridge** [comment]
Looks good

**Comment by mrdsaunders** [comment]
Merge (pull request) #96
