### ISSUE TITLE
ORA subtype 'Confidential report' field 'confidential_report'

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#94]
From mapping:
```
<symplectic_field name="confidential">
            <if test="type_of_work==Report">
                <ora_field>confidential_report</ora_field>
                <ora_field>sub_type_of_work='Report'</ora_field>
                <note>If the item is a Report, the type of work should be Report and the sub_type_of_work should be 'Confidential report', see TYPE OF WORK MAPPIGNS, below</note>
            </if>
            <if test="type_of_work!=Report">
                <ora_field>confidential_report</ora_field>
            </if>
</symplectic_field>
```

If ORA type/subtype = `Report/Confidential report` will there always be a value in ORA field `confidential_report` which will map to SE field `confidential`)?  If not, then perhaps we could add to the mappings to populate SE field `confidential` with a boolean True if that field is empty.

**Comment by tomwrobel** [comment]
@jjpartridge I hadn't considered the reverse of this mapping. What are your thoughts here? I confess not to being fully up to speed on this work type

**Comment by jjpartridge** [comment]
@mrdsaunders @tomwrobel That seems sensible to me. Where we have confidential report the sub-type should always be set. You could then use the presence of the sub-type value to set the Boolean for the field in SE.

**Comment by mrdsaunders** [comment]
I will add this to mapping for Harvest:
If ORA type/subtype = `Report/Confidential Report`:
    SE type will be `Report` and SE field `confidential` will be populated with `True`
else for all other ORA output types:
    if ORA field 'confidential_report' has a value (unlikely for other types however its in the original mapping), copy it to SE field `confidential`

**Comment by mrdsaunders** [comment]
Suggest:
```
<symplectic_field name="confidential">
            <if test="type_of_work==Report" and "subtype_of_work==Confidential report">
                <value = "True">
                <note>see TYPE OF WORK MAPPIGNS, below</note>
            </if>
            <if test="type_of_work!=Report" and "ora_field confidential_report has a value">
                <ora_field>confidential_report</ora_field>
            </if>
            <note>To clarify deposit: if SE type = report and SE confidential field is True, set type/subtype to Report/confidential report and map to ORA field confidential report. For other types if SE confidential field is True then map to ORA confidential_report </note>
        </symplectic_field>
```

**Comment by mrdsaunders** [comment]
Follow up questions:
- is the ORA field `confidential_report` ever populated for types other than `Report`?
- is it a Boolean? It seems so form the data model but the value in the sample mets is a string.

**Comment by mrdsaunders** [comment]
Agreed at ORA-SE 17/10/2019 that <ora_field>confidential_report</ora_field> no longer exists and confidentiality will only affect ORA subtype and SE field

**Comment by mrdsaunders** [comment]
```
<symplectic_field name="confidential">
            <if test="type_of_work==Report" and "subtype_of_work==Confidential report">
                <value = "True">
                <note>see TYPE OF WORK MAPPIGNS, below</note>
            </if>
            <note>ora field confidential_report no longer in data model</note>
</symplectic_field>
```
