### ISSUE TITLE
Confirm SE type <-> ORA subtype value mappings

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#97]
The value map in the Harvest Crosswalk doesn't match with the mapping on the Deposit Crosswalk. Can you confirm that the Harvest is the correct set of mappings (and should be used in reverse for Deposit)?

`Harvest`

```
<xwalk:value-map name="types">
      <xwalk:value-mapping from="Editorial" to="editorial comment" />
      <xwalk:value-mapping from="Review" to="review" />
      <xwalk:value-mapping from="Correspondence" to="rapid communication" />
      <xwalk:value-mapping from="Addendum" to="adendum" />
      <xwalk:value-mapping from="Corrigendum" to="corrigendum" />
      <xwalk:value-mapping from="Letter" to="letter" />
      <xwalk:otherwise-mapping action="ignore-this-value" />
    </xwalk:value-map>
```

`Deposit`
```
    <xwalk:value-map name="ora-subtype-work-mappings-from-subtype">
      <xwalk:value-mapping from="Review" to="Editorial" />
      <xwalk:value-mapping from="Rapid communication" to="Review" />
      <xwalk:otherwise-mapping action="ignore-this-value" />
    </xwalk:value-map>
```

**Comment by tomwrobel** [comment]
Jason, I think we need to work this out.

David, in the absence of other guidance, the deposit crosswalk is much more likely to be correct. Andrew Bennett and I didn't pay a lot of attention to the harvest crosswalk beyond the REF-related fields.

--
Tom Wrobel
Software Engineer - BDLSS
thomas.wrobel@bodleian.ox.ac.uk / 01865 277608

________________________________________

**Comment by mrdsaunders** [comment]
Background:
The `types` (effectively subtypes) field in SE is only used for journal articles and the possible values are those in the Harvest crosswalk, which makes me think they might actually be correct. 
All other crosswalking to ORA subtypes come from the actual SE `object.type` rather than the `types` field.

I guess this means that maybe we need to think more about which ORA type/subtype data could be useful in SE i.e. do we need to extend the use of subtypes in SE? That's a question for SE rather than you however.

**Comment by jjpartridge** [comment]
[Item_types_and_subtypes_mappings_20190718.xlsx](https://github.com/tomwrobel/ora_data_model/files/3706608/Item_types_and_subtypes_mappings_20190718.xlsx)

Perhaps this is useful.

**Comment by tomwrobel** [comment]
The correct mappings are in the excel file Jason sent.

If there is a sub type in SE, and a corresponding subtype in ORA4, then those two subtypes should be mapped (in both directions)

If there is a sub type in SE, but no corresponding subtype in ORA4, then the top level ORA work type should be selected, with no sub type, but I don't think there are any examples of this.

If there is a sub type in ORA4, but no corresponding subtype in SE, then the top level SE type should be selected with no sub type, e.g. ORA Physical Object subtype artefact maps to SE type artefact; ORA4 Internet Publication, subtype Blog maps to SE "internet publication"

Best wishes, and blue skies

Tom

--
Tom Wrobel
Software Engineer - BDLSS
thomas.wrobel@bodleian.ox.ac.uk / 01865 277608

________________________________________

**Comment by mrdsaunders** [comment]
Thanks - so in relation to the original question, it seems that the Harvest crosswalk is correct as it reflects that document for SE field `types` mapped to ORA4.
