### ISSUE TITLE
Abstract (as opposed to summary documentation) in mets

### ISSUE THREAD

**Issue by mrdsaunders** [tomwrobel/ora_data_model#98]
SE to ORA mapping refers to the following from SE field `abstract`:

```
<ora_symplectic_field_mappings>
        <symplectic_field name="abstract">
            <if test="object is a patent, physical object, or ephemera"><ora_field>summary_documentation</ora_field></if>
            <if test="object is NOT patent, physical object, or ephemera"><ora_field>abstract</ora_field></if>
        </symplectic_field>
```
However within the ORA fields to mets and sample mets there is only the following reference to abstract (`type = "summary documentation"`):
```
<mods:abstract>field:abstract</mods:abstract>
                    <mods:abstract type="summary_documentation">field:summary_documentation</mods:abstract>
                    <mods:note displayLabel="additional_information">field:additional_information</mods:note>
```
It is unclear how to distinguish in the mets between `abstract` and `summary documentation` as per the mapping.

Should there in fact be another possible tag `type="abstract"`?:

**Comment by tomwrobel** [comment]
Unless I've misunderstood (entirely likely)

The symplectic mappings document maps to field names, not to MODS/METS elements. The sample METS document shows how ORA field names are encoded, and both files together give the full XML mapping. So

Crosswalk doc: Symplectic field name "abstract", for patents, physical objects, ephemera maps to ORA field summary_documentation. METS file: ORA summary_documentation  is encoded as <mods:abstract type="summary_documentation"/>
Crosswalk doc: Symplectic field name "abstract", for NON patents, physical objects, or ephemera maps to ORA field abstract. METS file: ORA field abstract is encoded as <mods:abstract/>

I'm sure there's something I'm missing, so please prod me

--
Tom Wrobel
Software Engineer - BDLSS
thomas.wrobel@bodleian.ox.ac.uk / 01865 277608

________________________________________

**Comment by mrdsaunders** [comment]
Hi Tom. Thanks. You are correct. Apologies - I'm afraid I was suffering from my eyes swimming at the time and somehow misread `<mods:abstract type="summary_documentation">` as a child of `<mods:abstract>`.
